import { describe, expect, it } from 'vitest'
import { detectarIntencaoChat } from '@/domain/services/detector-chat'
const CASOS: Array<[string, string]> = [
  ["tem algum ncm de banana?", "ncm"],
  ["tem algum ncm pra queijo minas?", "ncm"],
  ["tem algum ncm de parafuso sextavado?", "ncm"],
  ["tem algum ncm pra camiseta de algodão?", "ncm"],
  ["tem algum ncm de carne bovina?", "ncm"],
  ["tem algum ncm pro frango resfriado?", "ncm"],
  ["tem algum ncm de pneu de caminhão?", "ncm"],
  ["tem algum ncm pra tinta acrílica?", "ncm"],
  ["tem algum ncm de café torrado?", "ncm"],
  ["tem algum ncm pro leite em pó?", "ncm"],
  ["qual o ncm de banana?", "ncm"],
  ["qual o ncm do queijo minas frescal?", "ncm"],
  ["qual o ncm pra camiseta de algodão?", "ncm"],
  ["qual o ncm da carne bovina congelada?", "ncm"],
  ["qual o ncm do parafuso de aço?", "ncm"],
  ["qual o ncm para pneu de caminhão?", "ncm"],
  ["qual o ncm do café torrado em grão?", "ncm"],
  ["qual o ncm da cerveja em lata?", "ncm"],
  ["qual o ncm do chocolate ao leite?", "ncm"],
  ["qual o ncm pro arroz branco?", "ncm"],
  ["qual o ncm do celular novo?", "ncm"],
  ["qual o ncm da panela de pressão?", "ncm"],
  ["qual o ncm do sofá de couro?", "ncm"],
  ["qual o ncm da bicicleta infantil?", "ncm"],
  ["ncm para banana?", "ncm"],
  ["ncm pra queijo coalho?", "ncm"],
  ["ncm de parafuso?", "ncm"],
  ["ncm para camiseta?", "ncm"],
  ["ncm do café em grão?", "ncm"],
  ["ncm pra pneu?", "ncm"],
  ["ncm da carne de frango?", "ncm"],
  ["ncm pro chocolate?", "ncm"],
  ["camiseta de algodão", "ncm"],
  ["vendo parafuso sextavado", "ncm"],
  ["queijo minas frescal", "ncm"],
  ["banana prata a granel", "ncm"],
  ["carne bovina congelada", "ncm"],
  ["café torrado em grão", "ncm"],
  ["leite em pó integral", "ncm"],
  ["pneu novo de borracha", "ncm"],
  ["tinta acrílica branca", "ncm"],
  ["caderno pautado de papel", "ncm"],
  ["panela de alumínio", "ncm"],
  ["cadeira de madeira", "ncm"],
  ["sapato de couro masculino", "ncm"],
  ["cerveja em garrafa de vidro", "ncm"],
  ["frango inteiro resfriado", "ncm"],
  ["azeite de oliva extravirgem", "ncm"],
  ["qual a tributação da banana?", "ncm"],
  ["qual a tributação do queijo minas?", "ncm"],
  ["qual a tributação de parafuso?", "ncm"],
  ["qual a tributação da camiseta de algodão?", "ncm"],
  ["qual a tributação do café torrado?", "ncm"],
  ["qual a tributação da carne bovina?", "ncm"],
  ["qual a tributação do pneu de caminhão?", "ncm"],
  ["qual a tributação da cerveja em lata?", "ncm"],
  ["qual a tributação do chocolate ao leite?", "ncm"],
  ["qual a tributação do frango resfriado?", "ncm"],
  ["08031000", "ncm"],
  ["ncm 08031000", "ncm"],
  ["o ncm 08031000 tá no sistema?", "ncm"],
  ["0803.10.00", "ncm"],
  ["esse ncm 09012100 tá certo?", "ncm"],
  ["produto com ncm 22030000", "ncm"],
  ["consulta o ncm 10063000 pra mim", "ncm"],
  ["ncm 85171200, qual a alíquota?", "ncm"],
  ["só tem esse ncm?", "ncm"],
  ["tem mais algum ncm?", "ncm"],
  ["quais ncms pra isso?", "ncm"],
  ["lista todos os ncm aí", "ncm"],
  ["tem outro ncm além desse?", "ncm"],
  ["mostra todos os ncm de banana", "ncm"],
  ["só existe esse ncm pra carne?", "ncm"],
  ["quais os ncm possíveis pro queijo?", "ncm"],
  ["cunsulta ncm da banana", "ncm"],
  ["tributasao da banana", "ncm"],
  ["claasificacao da carne", "ncm"],
  ["quall o ncm do queijo?", "ncm"],
  ["cunsulta o ncm do parafuso", "ncm"],
  ["qual o ncm da bananna?", "ncm"],
  ["me vê o ncm da banana?", "ncm"],
  ["preciso do ncm pra parafuso", "ncm"],
  ["fala aí o ncm da carne bovina", "ncm"],
  ["e aí, qual o ncm do queijo minas?", "ncm"],
  ["camiseta 100% algodão, qual o ncm?", "ncm"],
  ["produto feito de aço inox, qual o ncm?", "ncm"],
  ["queijo composto por leite de vaca, qual ncm?", "ncm"],
  ["parafuso de ferro para uso em obra, qual o ncm?", "ncm"],
  ["camiseta de poliéster para revenda, qual o ncm?", "ncm"],
  ["carne suína salgada, qual o ncm?", "ncm"],
  ["qual o nbs de yoga?", "nbs"],
  ["qual o nbs pra aula de pilates?", "nbs"],
  ["quanto fica R$ 100 no ncm 08031000?", "calculo"],
  ["calcula o imposto de R$ 500 pra mim", "calculo"],
  ["o que é IBS?", "conceito"],
  ["qual meu anexo do simples nacional?", "simples"],
  ["quais atividades o CNPJ 53.795.990/0001-68 tem?", "cnpj"],
  ["oi, tudo bem?", "saudacao"],
  ["como consulto um ncm aqui?", "ajuda"],
  ["me conta uma piada?", "generico"],
]
describe('varredura vocab — ncm', () => {
  it('100 casos roteiam como esperado', () => {
    const erros: string[] = []
    for (const [msg, esperado] of CASOS) {
      let obtido: string
      try { obtido = detectarIntencaoChat(msg).intencao } catch (e) { obtido = 'ERRO' }
      if (obtido !== esperado) erros.push(`${msg} → ${obtido} (esperado ${esperado})`)
    }
    expect(erros).toEqual([])
  })
})
