import { describe, expect, it } from 'vitest'
import { detectarIntencaoChat } from '@/domain/services/detector-chat'
const CASOS: Array<[string, string]> = [
  ["oi", "saudacao"],
  ["Oi!", "saudacao"],
  ["oi!!", "saudacao"],
  ["olá", "saudacao"],
  ["Ola!", "saudacao"],
  ["bom dia!", "saudacao"],
  ["Bom dia!!", "saudacao"],
  ["boa tarde", "saudacao"],
  ["Boa tarde!", "saudacao"],
  ["boa noite!!", "saudacao"],
  ["oi, tudo bem?", "saudacao"],
  ["Oi, tudo bem??", "saudacao"],
  ["olá, tudo bem?", "saudacao"],
  ["bom dia, tudo bem?", "saudacao"],
  ["boa tarde, tudo bem?", "saudacao"],
  ["boa noite, tudo bem?", "saudacao"],
  ["oi, tudo certo?", "saudacao"],
  ["bom dia, tudo certo??", "saudacao"],
  ["oi, como vai?", "saudacao"],
  ["olá, e vc?", "saudacao"],
  ["obrigado!", "conversa_leve"],
  ["Obrigado!!", "conversa_leve"],
  ["muito obrigado, viu?", "conversa_leve"],
  ["obrigada!", "conversa_leve"],
  ["obg!", "conversa_leve"],
  ["obg, valeu!", "conversa_leve"],
  ["valeu pela ajuda!", "conversa_leve"],
  ["vlw mesmo, obrigado!", "conversa_leve"],
  ["tchau, até mais!", "conversa_leve"],
  ["tchau, ate logo!", "conversa_leve"],
  ["ok!", "conversa_leve"],
  ["Ok, entendi!", "conversa_leve"],
  ["beleza!", "conversa_leve"],
  ["blz, entendi!", "conversa_leve"],
  ["entendi, perfeito!", "conversa_leve"],
  ["show, valeu!", "conversa_leve"],
  ["legal, perfeito!", "conversa_leve"],
  ["perfeito, obrigado!", "conversa_leve"],
  ["show de bola, valeu!", "conversa_leve"],
  ["ok, beleza, show!", "conversa_leve"],
  ["o que vc pode fazer?", "capacidades"],
  ["o que você pode fazer??", "capacidades"],
  ["o que vc sabe fazer?", "capacidades"],
  ["o que você faz?", "capacidades"],
  ["o que vc consegue fazer?", "capacidades"],
  ["quais suas funções?", "capacidades"],
  ["quais sao suas funcoes??", "capacidades"],
  ["quais seus recursos?", "capacidades"],
  ["quais seus recursos, pfv?", "capacidades"],
  ["suas capacidades, pfv?", "capacidades"],
  ["lista de recursos, por favor?", "capacidades"],
  ["para que vc serve?", "capacidades"],
  ["para que serve vc??", "capacidades"],
  ["como vc funciona?", "capacidades"],
  ["como vc pode me ajudar?", "capacidades"],
  ["quem é vc?", "capacidades"],
  ["quem e voce??", "capacidades"],
  ["o que vc é?", "capacidades"],
  ["se apresente, por favor!", "capacidades"],
  ["sua apresentação, pfv?", "capacidades"],
  ["como consulto um NCM?", "ajuda"],
  ["como consultar, pfv?", "ajuda"],
  ["como calculo o imposto, me ensina?", "ajuda"],
  ["como calcular o DAS, passo a passo?", "ajuda"],
  ["como gero um relatório?", "ajuda"],
  ["como gerar o PDF, tbm?", "ajuda"],
  ["como uso a calculadora?", "ajuda"],
  ["como usar o sistema, pq sou novo?", "ajuda"],
  ["como faço pra consultar, me ensina?", "ajuda"],
  ["me ensina a usar, por favor?", "ajuda"],
  ["me ensina passo a passo?", "ajuda"],
  ["me explica como usa a consulta?", "ajuda"],
  ["me ajuda a usar o app, pfv?", "ajuda"],
  ["tem tutorial de como usar?", "ajuda"],
  ["tutorial, por favor??", "ajuda"],
  ["passo a passo pra gerar, pfv?", "ajuda"],
  ["passo a passo de como calcular?", "ajuda"],
  ["como funciona o sistema pra consultar?", "ajuda"],
  ["como funciona a tela de consulta?", "ajuda"],
  ["como consulto, vc me ensina?", "ajuda"],
  ["me leva pra calculadora!", "navegar"],
  ["me leva para a consulta, pfv?", "navegar"],
  ["oi, me leva pra calculadora?", "navegar"],
  ["olá, me leva para a consulta de NCM?", "navegar"],
  ["oi, abre a calculadora pra mim?", "navegar"],
  ["abre a tela da consulta, por favor", "navegar"],
  ["abra a calculadora, pfv?", "navegar"],
  ["abrir a consulta de NBS, por favor?", "navegar"],
  ["quero ver a calculadora, por favor!", "navegar"],
  ["quero ver o simples, tbm?", "navegar"],
  ["quero ver a tela de serviços?", "navegar"],
  ["acessar o lote, pfv?", "navegar"],
  ["acessar a NFe, por favor?", "navegar"],
  ["acessar os produtos, vc pode?", "navegar"],
  ["ir para a calculadora?", "navegar"],
  ["ir para os auxiliares, pfv?", "navegar"],
  ["leva para a legislação, por favor?", "navegar"],
  ["levar para a tela do simples?", "navegar"],
  ["mostra a tela do lote, pfv?", "navegar"],
  ["va para a consulta, por favor!", "navegar"],
  ["a base está pronta?", "status"],
  ["base pronta?", "status"],
  ["base carregada?", "status"],
  ["base carregada, pfv?", "status"],
  ["base atualizada?", "status"],
  ["quantos NCM tem na base?", "status"],
  ["quantos ncm cadastrados?", "status"],
  ["status do sistema, pfv?", "status"],
  ["qual o status?", "status"],
  ["sistema ok?", "status"],
  ["o sistema está ok?", "status"],
  ["sistema pronto?", "status"],
  ["sistema atualizado?", "status"],
  ["tá tudo carregado?", "status"],
  ["versão da base, por favor?", "status"],
  ["qual a versão da base?", "status"],
  ["base pronta? sistema ok?", "status"],
  ["a base está pronta? vc confirma?", "status"],
  ["quantos ncm, pq preciso saber?", "status"],
  ["status, tudo carregado?", "status"],
]
describe('varredura vocab — social/orientação', () => {
  it('100 casos roteiam como esperado', () => {
    const erros: string[] = []
    for (const [msg, esperado] of CASOS) {
      let obtido: string
      try { obtido = detectarIntencaoChat(msg).intencao } catch (e) { obtido = 'ERRO' }
      if (obtido !== esperado) erros.push(`${msg} → ${obtido} (esperado ${esperado})`)
    }
    expect(erros).toEqual([])
  })
})
