import { describe, expect, it } from 'vitest'
import { detectarIntencaoChat } from '@/domain/services/detector-chat'
const CASOS: Array<[string, string]> = [
  ["quero cadastrar um produto", "cadastrar_produto"],
  ["preciso cadastrar um produto novo", "cadastrar_produto"],
  ["gostaria de cadastrar um produto", "cadastrar_produto"],
  ["quero cadastrar um produto novo no sistema", "cadastrar_produto"],
  ["preciso cadastrar o produto queijo minas", "cadastrar_produto"],
  ["cadastrar um produto novo", "cadastrar_produto"],
  ["cadastrar produto camiseta de algodao", "cadastrar_produto"],
  ["quero cadastrar mais um produto", "cadastrar_produto"],
  ["preciso cadastrar esse produto aqui", "cadastrar_produto"],
  ["cadastrar o produto SKU 1001", "cadastrar_produto"],
  ["quero cadastrar o produto com NCM 08030000", "cadastrar_produto"],
  ["cadastrar novo produto pra mim", "cadastrar_produto"],
  ["cadastra esse produto", "cadastrar_produto"],
  ["cadastra um produto novo pra mim", "cadastrar_produto"],
  ["cadastra o produto SKU 123", "cadastrar_produto"],
  ["por favor cadastra esse produto", "cadastrar_produto"],
  ["cadastra mais um produto", "cadastrar_produto"],
  ["cadastra este produto aqui", "cadastrar_produto"],
  ["oi, cadastra um produto novo", "cadastrar_produto"],
  ["cadastra o produto banana prata", "cadastrar_produto"],
  ["cadastra produto novo com composicao algodao 100%", "cadastrar_produto"],
  ["cadastra esse produto pra revenda", "cadastrar_produto"],
  ["cadastra o produto nota 10", "cadastrar_produto"],
  ["cadastra um produto pra mim por favor", "cadastrar_produto"],
  ["salvar produto novo", "cadastrar_produto"],
  ["quero salvar um produto", "cadastrar_produto"],
  ["salva esse produto pra mim", "cadastrar_produto"],
  ["salvar um produto novo aqui", "cadastrar_produto"],
  ["quero salvar esse produto", "cadastrar_produto"],
  ["salva o produto SKU 55", "cadastrar_produto"],
  ["salvar novo produto agora", "cadastrar_produto"],
  ["preciso salvar um produto", "cadastrar_produto"],
  ["salva esse produto novo", "cadastrar_produto"],
  ["salvar o produto arroz integral", "cadastrar_produto"],
  ["adiciona um produto pra mim", "cadastrar_produto"],
  ["quero adicionar um produto novo", "cadastrar_produto"],
  ["adicionar um produto", "cadastrar_produto"],
  ["adiciona esse produto", "cadastrar_produto"],
  ["preciso adicionar um produto", "cadastrar_produto"],
  ["adicionar novo produto ao cadastro", "cadastrar_produto"],
  ["adiciona o produto SKU 200", "cadastrar_produto"],
  ["quero adicionar mais um produto", "cadastrar_produto"],
  ["adiciona esse produto novo aqui", "cadastrar_produto"],
  ["adicionar o produto feijao preto", "cadastrar_produto"],
  ["adiciona um produto novo agora", "cadastrar_produto"],
  ["por favor adiciona esse produto", "cadastrar_produto"],
  ["registra o produto X", "cadastrar_produto"],
  ["quero registrar um produto", "cadastrar_produto"],
  ["registrar novo produto", "cadastrar_produto"],
  ["registra esse produto pra mim", "cadastrar_produto"],
  ["preciso registrar um produto novo", "cadastrar_produto"],
  ["registrar o produto SKU 77", "cadastrar_produto"],
  ["registra um produto novo aqui", "cadastrar_produto"],
  ["quero registrar o produto leite integral", "cadastrar_produto"],
  ["criar um produto novo", "cadastrar_produto"],
  ["cria um produto pra mim", "cadastrar_produto"],
  ["quero criar um produto", "cadastrar_produto"],
  ["cria esse produto novo", "cadastrar_produto"],
  ["preciso criar um produto", "cadastrar_produto"],
  ["criar novo produto agora", "cadastrar_produto"],
  ["cria o produto SKU 300", "cadastrar_produto"],
  ["quero criar mais um produto", "cadastrar_produto"],
  ["atualiza o produto SKU 1", "cadastrar_produto"],
  ["quero atualizar um produto", "cadastrar_produto"],
  ["atualizar produto existente", "cadastrar_produto"],
  ["atualiza esse produto pra mim", "cadastrar_produto"],
  ["preciso atualizar o produto 10", "cadastrar_produto"],
  ["atualizar o produto arroz branco", "cadastrar_produto"],
  ["atualiza o produto novo", "cadastrar_produto"],
  ["quero atualizar esse produto", "cadastrar_produto"],
  ["como faco para cadastrar um produto?", "ajuda"],
  ["me ensina a cadastrar um produto", "ajuda"],
  ["tutorial para cadastrar produto", "ajuda"],
  ["passo a passo para cadastrar um produto", "ajuda"],
  ["como usar o cadastro de produto?", "ajuda"],
  ["como consulto um produto cadastrado?", "ajuda"],
  ["me explica como cadastrar um produto", "ajuda"],
  ["como gero a lista de produtos?", "ajuda"],
  ["tem algum ncm de banana?", "ncm"],
  ["qual o ncm do queijo minas?", "ncm"],
  ["produto com reducao de IBS?", "ncm"],
  ["esse produto possui reducao?", "ncm"],
  ["qual a tributacao da carne bovina?", "ncm"],
  ["o NCM da banana prata possui reducao?", "ncm"],
  ["classifica esse queijo pra mim", "ncm"],
  ["qual a classificacao fiscal do parafuso?", "ncm"],
  ["ncm 08030000 qual a aliquota?", "ncm"],
  ["me diz o ncm do arroz integral", "ncm"],
  ["salvar essa empresa", "cnpj"],
  ["cadastrar empresa com cnpj 53795990000168", "cnpj"],
  ["o cnpj 53.795.990/0001-68 ta cadastrado?", "cnpj"],
  ["quais atividades o CNPJ 53795990000168 tem?", "cnpj"],
  ["consultar cnpj 53795990000168", "cnpj"],
  ["dados do cnpj 53795990000168", "cnpj"],
  ["quais meus clientes?", "clientes"],
  ["lista meus clientes", "clientes"],
  ["quantos clientes eu tenho?", "clientes"],
  ["qual produto mais vendido?", "dados"],
  ["quais top produtos desse cliente?", "dados"],
  ["quais produtos geram mais credito?", "dados"],
]
describe('varredura vocab — cadastro-produto', () => {
  it('100 casos roteiam como esperado', () => {
    const erros: string[] = []
    for (const [msg, esperado] of CASOS) {
      let obtido: string
      try { obtido = detectarIntencaoChat(msg).intencao } catch (e) { obtido = 'ERRO' }
      if (obtido !== esperado) erros.push(`${msg} → ${obtido} (esperado ${esperado})`)
    }
    expect(erros).toEqual([])
  })
})
