import { describe, expect, it } from 'vitest'
import { detectarIntencaoChat } from '@/domain/services/detector-chat'
const CASOS: Array<[string, string]> = [
  ["gera um relatório dessa conversa", "relatorio"],
  ["gera um relatório desse cálculo para mim", "relatorio"],
  ["exporta um relatório em pdf", "relatorio"],
  ["exportar relatório em csv do cálculo", "relatorio"],
  ["baixa o relatório em pdf dessa conversa", "relatorio"],
  ["baixar relatório em json", "relatorio"],
  ["gera o relatório em pdf por favor", "relatorio"],
  ["obrigado, gera um relatório dessa conversa", "relatorio"],
  ["obrigado, gera um relatório desse cálculo", "relatorio"],
  ["obrigado, gera um relatório em pdf", "relatorio"],
  ["preciso do relatório dessa conversa em pdf", "relatorio"],
  ["me manda o relatório em csv", "relatorio"],
  ["gera um texto com o resumo dessa conversa", "relatorio"],
  ["gera um documento com esse cálculo", "relatorio"],
  ["exporta essa conversa em pdf", "relatorio"],
  ["exportar o cálculo em csv", "relatorio"],
  ["baixa esse cálculo em json para mim", "relatorio"],
  ["quero o relatório completo em pdf", "relatorio"],
  ["emite um relatório do cálculo em pdf", "relatorio"],
  ["salva um relatório dessa conversa em pdf", "relatorio"],
  ["gera o relatório dessa conversa em txt", "relatorio"],
  ["faz um relatório desse cálculo em csv", "relatorio"],
  ["manda o relatório da conversa no pdf", "relatorio"],
  ["preciso baixar o documento dessa conversa", "relatorio"],
  ["exporta o relatório com o resumo do atendimento", "relatorio"],
  ["qual melhor, Anexo III ou V?", "comparativo"],
  ["qual o melhor enquadramento, III ou V?", "comparativo"],
  ["qual compensa mais para mim, III ou V?", "comparativo"],
  ["qual vale mais a pena, III ou V?", "comparativo"],
  ["vale a pena migrar do Anexo III para o V?", "comparativo"],
  ["vale a pena sair do III e ir para o V?", "comparativo"],
  ["compara o Anexo III com o Anexo V para mim", "comparativo"],
  ["compara III e V no meu caso", "comparativo"],
  ["faz um comparativo entre o III e o V", "comparativo"],
  ["quero um comparativo de III ou V", "comparativo"],
  ["estou entre III ou V, qual fica melhor?", "comparativo"],
  ["III ou V para uma empresa de serviços?", "comparativo"],
  ["III x V: qual cobra menos?", "comparativo"],
  ["convencional ou híbrido, qual escolher?", "comparativo"],
  ["para mim, convencional ou híbrido?", "comparativo"],
  ["qual anexo fica melhor para o meu caso?", "comparativo"],
  ["qual anexo compensa mais?", "comparativo"],
  ["III vs V, qual a vantagem de cada um?", "comparativo"],
  ["híbrido vs convencional: qual a diferença de valor?", "comparativo"],
  ["vale a pena ficar no III ou migrar para o V?", "comparativo"],
  ["qual melhor regime para pagar menos, III ou V?", "comparativo"],
  ["me ajuda a comparar o III com o V", "comparativo"],
  ["qual compensa: III ou V?", "comparativo"],
  ["convencional ou híbrido para o meu perfil?", "comparativo"],
  ["faz uma comparação entre III e V", "comparativo"],
  ["o que é IBS?", "conceito"],
  ["o que é CBS?", "conceito"],
  ["o que é NCM?", "conceito"],
  ["o que é NBS?", "conceito"],
  ["o que é Fator R?", "conceito"],
  ["o que é sublimite?", "conceito"],
  ["o que é DAS?", "conceito"],
  ["o que é CST?", "conceito"],
  ["o que é CFOP?", "conceito"],
  ["o que significa IBS?", "conceito"],
  ["o que significa CBS na prática?", "conceito"],
  ["o que significa Fator R?", "conceito"],
  ["o que significa sublimite?", "conceito"],
  ["me explica o que é IBS?", "conceito"],
  ["me explica o que é NCM?", "conceito"],
  ["me explica o que é Fator R?", "conceito"],
  ["explica o que é CBS?", "conceito"],
  ["qual a diferença entre IBS e CBS?", "conceito"],
  ["me explica a diferença entre o Anexo III e o Anexo V?", "conceito"],
  ["qual a diferença entre o III e o V do Simples?", "conceito"],
  ["o que é crédito de IBS?", "conceito"],
  ["conceito de sublimite", "conceito"],
  ["definição de Fator R", "conceito"],
  ["para que serve o DAS?", "conceito"],
  ["o que são os anexos do Simples?", "conceito"],
  ["xyzblt", "generico"],
  ["asdfgh qwer", "generico"],
  ["kkkk", "generico"],
  ["e para 50 mil?", "generico"],
  ["o que você acha?", "generico"],
  ["me ajuda", "generico"],
  ["bom...", "generico"],
  ["hmm, sei lá", "generico"],
  ["e agora?", "generico"],
  ["e depois?", "generico"],
  ["como assim?", "generico"],
  ["pode repetir isso?", "generico"],
  ["não ficou claro", "generico"],
  ["só olhando por enquanto", "generico"],
  ["deixa eu ver com calma", "generico"],
  ["um momento, já volto", "generico"],
  ["me conta uma piada", "generico"],
  ["qual a previsão do tempo para amanhã?", "generico"],
  ["quem descobriu o Brasil?", "generico"],
  ["me indica um filme bom", "generico"],
  ["você gosta de música?", "generico"],
  ["estou com dor de cabeça forte", "generico"],
  ["como está o clima hoje?", "generico"],
  ["qual seu hobby favorito?", "generico"],
  ["meu filho está com febre, o que faço?", "generico"],
]
describe('varredura vocab — misto', () => {
  it('100 casos roteiam como esperado', () => {
    const erros: string[] = []
    for (const [msg, esperado] of CASOS) {
      let obtido: string
      try { obtido = detectarIntencaoChat(msg).intencao } catch (e) { obtido = 'ERRO' }
      if (obtido !== esperado) erros.push(`${msg} → ${obtido} (esperado ${esperado})`)
    }
    expect(erros).toEqual([])
  })
})
