import { describe, expect, it } from 'vitest'
import { detectarIntencaoChat } from '@/domain/services/detector-chat'
const CASOS: Array<[string, string]> = [
  ["meu DAS no Anexo III com RBT12 500 mil", "simples"],
  ["calcula meu das do anexo 3 com receita de 40 mil", "simples"],
  ["quanto fica meu DAS no anexo iii com rbt12 de 800 mil", "simples"],
  ["simula meu das anexo III, folha de 15 mil", "simples"],
  ["meu das do simples no Anexo 3 deu quanto este mês", "simples"],
  ["recolho pelo anexo iii, rbt de 600 mil, quanto pago", "simples"],
  ["das anexo III com faturamento de R$ 50 mil no mês", "simples"],
  ["estou no Anexo III, minha receita foi 35 mil, calcula o das", "simples"],
  ["anexo III com rbt12 1,2 milhão, qual o valor do das", "simples"],
  ["pago das pelo anexo iii com folha alta, simula pra mim", "simples"],
  ["meu DAS no Anexo V com RBT12 900 mil", "simples"],
  ["anexo V, rbt12 1 milhão, receita 80 mil", "simples"],
  ["calcula das anexo 5 com folha de 20 mil", "simples"],
  ["estou no anexo IV, rbt12 700 mil, quanto pago de das", "simples"],
  ["simula anexo V com rbt 2 milhões e folha baixa", "simples"],
  ["meu das do anexo IV com receita bruta de 60 mil", "simples"],
  ["anexo 4 com folha de pagamento de 25 mil", "simples"],
  ["recolho no anexo V, minha folha foi 10 mil, calcula", "simples"],
  ["das anexo 5, rbt12 400 mil, faturamento 45 mil", "simples"],
  ["estou no Anexo IV da construção, rbt12 1 milhão", "simples"],
  ["meu rbt12 é 500 mil, calcula meu simples", "simples"],
  ["com rbt12 de 2 milhões, quanto pago no simples", "simples"],
  ["rbt dos últimos 12 meses em 750 mil, simula o das", "simples"],
  ["minha receita acumulada de 12 meses deu 300 mil, calcula o das", "simples"],
  ["faturamento dos últimos 12 meses 900 mil, quanto fica o simples", "simples"],
  ["rbt12 de 3 milhões, ainda pago pelo anexo III", "simples"],
  ["meu RBT12 passou de 1 milhão, recalcula meu DAS", "simples"],
  ["receita bruta total dos 12 meses 450 mil, quanto dá o das", "simples"],
  ["com RBT de 180 mil, qual minha faixa no simples", "simples"],
  ["rbt12 600 mil e receita do mês 70 mil, simula", "simples"],
  ["minha folha de pagamento é 30 mil, calcula o fator R", "simples"],
  ["folha de 12 mil com receita de 50 mil, meu fator R fecha", "simples"],
  ["fator R com folha alta, anexo III, rbt12 500 mil", "simples"],
  ["pago 28% de folha sobre a receita, caio no anexo III", "simples"],
  ["minha folha soma 8 mil e faturo 60 mil, calcula o das", "simples"],
  ["folha de pagamento baixa, vou para o anexo V", "simples"],
  ["com folha de 40 mil e rbt12 800 mil, simula meu simples", "simples"],
  ["o fator R da minha empresa com folha de 15 mil", "simples"],
  ["inclui minha folha no cálculo do simples, rbt12 550 mil", "simples"],
  ["folha zerada este mês, meu das do anexo V fica quanto", "simples"],
  ["minha receita bruta do mês foi 90 mil, calcula o das", "simples"],
  ["faturei 30 mil este mês no simples, quanto pago", "simples"],
  ["receita de 120 mil no trimestre, simula meu simples", "simples"],
  ["meu faturamento mensal é 25 mil, sou do simples", "simples"],
  ["receita bruta de R$ 200 mil no ano, calcula meu das", "simples"],
  ["faturei R$ 80 mil no anexo III, quanto fica", "simples"],
  ["minha receita subiu para 100 mil, recalcula o das", "simples"],
  ["com receita de 15 mil mensais, pago quanto de simples", "simples"],
  ["faturamento de 500 mil no ano, meu rbt12 estoura", "simples"],
  ["receita do mês 55 mil com folha 18 mil, simula o das", "simples"],
  ["o sublimite de 3,6 milhões me pega", "simples"],
  ["passei do sublimite estadual, meu das muda", "simples"],
  ["sublimite de R$ 3,6 milhões, ainda recolho ICMS no das", "simples"],
  ["meu rbt12 bateu 4 milhões, cai no sublimite", "simples"],
  ["estourei o sublimite, calcula meu simples separado", "simples"],
  ["sublimite estadual e meu anexo III com rbt12 alto", "simples"],
  ["com receita de 4 milhões no ano, passo do sublimite", "simples"],
  ["o sublimite me tira do simples", "simples"],
  ["sou MEI, quanto pago por mês", "simples"],
  ["sou mei e faturo 8 mil, meu das aumenta", "simples"],
  ["mei com receita de 100 mil no ano, simula", "simples"],
  ["ultrapassei o limite do mei, vou para o simples", "simples"],
  ["pago mei e minha folha é só eu, calcula", "simples"],
  ["quero sair do mei para o simples, rbt12 200 mil", "simples"],
  ["sou MEI, faturei R$ 10 mil este mês", "simples"],
  ["mei com rbt12 de 81 mil, estoura o teto", "simples"],
  ["sou comércio, faturo 30 mil por mês", "simples"],
  ["tenho uma loja no simples e faturo R$ 40 mil mensais", "simples"],
  ["sou da indústria, receita de 200 mil no mês", "simples"],
  ["tenho escritório de advocacia com rbt12 600 mil", "simples"],
  ["sou médico e faturo 50 mil por mês no simples", "simples"],
  ["sou contador com receita de 25 mil mensais", "simples"],
  ["tenho empresa de software, rbt12 1 milhão", "simples"],
  ["sou engenheiro, minha folha é 12 mil", "simples"],
  ["calcula meu simples com receita de 60 mil", "simples"],
  ["quanto pago de simples este mês com rbt12 900 mil", "simples"],
  ["simula meu imposto do simples nacional, anexo III", "simples"],
  ["estou no simples nacional e faturei 45 mil", "simples"],
  ["minha guia do simples venceu, recalcula com rbt12 atual", "simples"],
  ["optante do simples com folha 20 mil e receita 70 mil", "simples"],
  ["o que é Fator R?", "conceito"],
  ["o que significa sublimite?", "conceito"],
  ["me explica o que é DAS?", "conceito"],
  ["o que é RBT12?", "conceito"],
  ["me explique o anexo III do simples", "conceito"],
  ["o que são os anexos do Simples Nacional?", "conceito"],
  ["qual a diferença entre IBS e CBS?", "conceito"],
  ["o que significa RBT12 no simples?", "conceito"],
  ["qual melhor, anexo III ou V?", "comparativo"],
  ["qual vale mais a pena para minha empresa?", "comparativo"],
  ["compara o regime convencional com o híbrido", "comparativo"],
  ["anexo III vs V, qual compensa mais?", "comparativo"],
  ["quanto fica R$ 1000 no ncm 08031000?", "calculo"],
  ["calcula IBS e CBS de R$ 2000 no NCM 84713000", "calculo"],
  ["qual o imposto de R$ 5000 no código 22042100?", "calculo"],
  ["simula R$ 3500 no NCM 09012100", "calculo"],
  ["qual NBS para aula de yoga?", "nbs"],
  ["qual o NBS de aula de pilates?", "nbs"],
  ["qual código de serviço para curso de inglês?", "nbs"],
  ["qual NBS para massagem terapêutica?", "nbs"],
]
describe('varredura vocab — simples', () => {
  it('100 casos roteiam como esperado', () => {
    const erros: string[] = []
    for (const [msg, esperado] of CASOS) {
      let obtido: string
      try { obtido = detectarIntencaoChat(msg).intencao } catch (e) { obtido = 'ERRO' }
      if (obtido !== esperado) erros.push(`${msg} → ${obtido} (esperado ${esperado})`)
    }
    expect(erros).toEqual([])
  })
})
