import { describe, expect, it } from 'vitest'
import { detectarIntencaoChat } from '@/domain/services/detector-chat'
const CASOS: Array<[string, string]> = [
  ["explica o art. 128 da LC 214", "legislacao"],
  ["o que diz o artigo 137 sobre cesta básica", "legislacao"],
  ["me explica o art. 138 §2º da lei complementar 214", "legislacao"],
  ["onde a lei fala de diferimento", "legislacao"],
  ["o que diz a LC 214 sobre cesta básica", "legislacao"],
  ["pesquisa na lei sobre imóveis", "legislacao"],
  ["qual artigo trata de bares e restaurantes na LC 214", "legislacao"],
  ["me explica o art. 261 da LC 214", "legislacao"],
  ["texto da lei sobre cashback", "legislacao"],
  ["explica o artigo 135 da lcp 214", "legislacao"],
  ["o que diz o art. 142 sobre produtos in natura", "legislacao"],
  ["art. 149 explica sobre transição de 2026 a 2033", "legislacao"],
  ["onde a LC 214 fala de imóveis", "legislacao"],
  ["o que a lei complementar 214 diz sobre turismo", "legislacao"],
  ["pesquisa na LC 214 sobre prouni", "legislacao"],
  ["qual artigo da LC 214 trata do comitê gestor", "legislacao"],
  ["texto da LC 214 sobre cesta básica nacional", "legislacao"],
  ["explica o art. 156 sobre cashback para famílias", "legislacao"],
  ["o que diz o art. 161 sobre o comitê gestor", "legislacao"],
  ["art. 174 da LC 214 fala sobre o quê", "legislacao"],
  ["me explica o artigo 128 sobre IBS na cesta básica", "legislacao"],
  ["o que diz a lei sobre alimentos in natura", "legislacao"],
  ["onde a lei complementar fala de diferimento", "legislacao"],
  ["pesquisa diferimento na LC 214", "legislacao"],
  ["qual artigo trata de turismo na LC 214", "legislacao"],
  ["texto da lei complementar 214 sobre imóveis", "legislacao"],
  ["explica o art. 183 da LC 214 sobre locação de imóveis", "legislacao"],
  ["o que diz o artigo 214 sobre bares e restaurantes", "legislacao"],
  ["art. 225 §1º da LC 214 me explica", "legislacao"],
  ["onde a LC 214 trata da transição de 2026 a 2033", "legislacao"],
  ["o que a LC 214 fala sobre cashback", "legislacao"],
  ["pesquisa na lei complementar sobre comitê gestor", "legislacao"],
  ["qual artigo fala de cesta básica na LC 214", "legislacao"],
  ["me explica o art. 132 sobre redução de alíquota na lei", "legislacao"],
  ["explica o artigo 144 da LC 214", "legislacao"],
  ["o que diz o art. 150 sobre regimes específicos", "legislacao"],
  ["art. 152 da lei complementar explica sobre turismo", "legislacao"],
  ["onde a lei fala sobre prouni", "legislacao"],
  ["o que diz a LC 214 sobre produtos in natura", "legislacao"],
  ["pesquisa na LC sobre bares e restaurantes", "legislacao"],
  ["qual artigo da lei complementar 214 trata de cashback", "legislacao"],
  ["texto da LC 214 sobre transição tributária", "legislacao"],
  ["explica o art. 167 sobre crédito na LC 214", "legislacao"],
  ["o que diz o artigo 168 sobre débito do imposto", "legislacao"],
  ["art. 190 da LC 214 sobre alíquota de referência", "legislacao"],
  ["onde a lei complementar 214 fala de cesta básica", "legislacao"],
  ["o que diz a lei sobre diferimento na transição", "legislacao"],
  ["pesquisa comitê gestor na LC 214", "legislacao"],
  ["qual artigo trata de imóveis na lei complementar 214", "legislacao"],
  ["me explica o art. 201 sobre turismo", "legislacao"],
  ["explica o art. 205 da lei sobre transporte coletivo", "legislacao"],
  ["o que diz o art. 210 da LC 214 sobre educação", "legislacao"],
  ["art. 215 explica a regra do cashback", "legislacao"],
  ["onde a LC 214 fala de alíquota reduzida para cesta básica", "legislacao"],
  ["o que diz a lei complementar sobre itens in natura", "legislacao"],
  ["pesquisa na lei sobre transição de 2026 a 2033", "legislacao"],
  ["qual artigo da LC 214 fala de prouni", "legislacao"],
  ["texto da lei sobre comitê gestor nacional", "legislacao"],
  ["explica o art. 219 sobre bares e restaurantes", "legislacao"],
  ["o que diz o art. 223 da LC 214", "legislacao"],
  ["art. 231 da lei complementar sobre imóveis residenciais", "legislacao"],
  ["onde a lei fala de cashback para baixa renda", "legislacao"],
  ["o que a LC 214 diz sobre bares e restaurantes", "legislacao"],
  ["pesquisa turismo na lei complementar 214", "legislacao"],
  ["qual artigo trata da cesta estendida na LC 214", "legislacao"],
  ["me explica o art. 237 da LC 214 sobre eventos", "legislacao"],
  ["explica o artigo 241 sobre redução do IBS", "legislacao"],
  ["o que diz o art. 245 da lei sobre locação", "legislacao"],
  ["art. 250 da LC 214 trata do quê", "legislacao"],
  ["onde a lei complementar fala sobre turismo", "legislacao"],
  ["o que diz a LC 214 sobre o comitê gestor", "legislacao"],
  ["pesquisa itens in natura na LC 214", "legislacao"],
  ["qual artigo da lei complementar 214 fala sobre diferimento", "legislacao"],
  ["texto da LC 214 sobre prouni e educação", "legislacao"],
  ["explica o art. 255 da LC 214 sobre fiscalização", "legislacao"],
  ["o que diz o artigo 260 sobre disposições finais", "legislacao"],
  ["art. 262 §3º da LC 214 me explica por favor", "legislacao"],
  ["onde a LC 214 lista os itens da cesta básica", "legislacao"],
  ["o que diz a lei complementar 214 sobre imóveis e locação", "legislacao"],
  ["pesquisa cesta básica na lei complementar 214", "legislacao"],
  ["meu DAS no Anexo III vence quando", "simples"],
  ["estou no Anexo III e faturo 30 mil por mês", "simples"],
  ["calcula meu DAS do Anexo V com folha de 8 mil", "simples"],
  ["minha empresa é do Anexo III do Simples", "simples"],
  ["Anexo III", "simples"],
  ["Anexo V com receita de 500 mil", "simples"],
  ["sou do Simples Anexo I e vendo roupas", "simples"],
  ["meu DAS do Simples atrasou como regularizo", "simples"],
  ["o que é Fator R", "conceito"],
  ["o que é sublimite", "conceito"],
  ["o que é IBS", "conceito"],
  ["o que significa CBS", "conceito"],
  ["o que é RBT12", "conceito"],
  ["me explica o que é DAS", "conceito"],
  ["qual a diferença entre IBS e CBS", "conceito"],
  ["qual NBS para hotelaria", "nbs"],
  ["qual o NBS de hospedagem", "nbs"],
  ["qual NBS para aula de yoga", "nbs"],
  ["qual NBS para transporte de pessoas", "nbs"],
  ["qual NBS para hospedagem em hotel fazenda", "nbs"],
]
describe('varredura vocab — legislacao', () => {
  it('100 casos roteiam como esperado', () => {
    const erros: string[] = []
    for (const [msg, esperado] of CASOS) {
      let obtido: string
      try { obtido = detectarIntencaoChat(msg).intencao } catch (e) { obtido = 'ERRO' }
      if (obtido !== esperado) erros.push(`${msg} → ${obtido} (esperado ${esperado})`)
    }
    expect(erros).toEqual([])
  })
})
