import { describe, expect, it } from 'vitest'
import { detectarIntencaoChat } from '@/domain/services/detector-chat'
const CASOS: Array<[string, string]> = [
  ["qual o nbs para aula de yoga?", "nbs"],
  ["qual nbs de aula de ingles?", "nbs"],
  ["me diz o nbs para aula de pilates?", "nbs"],
  ["preciso do nbs para curso de violao?", "nbs"],
  ["qual o nbs pra aula de canto?", "nbs"],
  ["q o nbs pra curso de culinaria?", "nbs"],
  ["qual nbs para treinamento de equipe?", "nbs"],
  ["me fala o nbs de aula particular de matematica?", "nbs"],
  ["qual o nbs para workshop de fotografia?", "nbs"],
  ["nbs para mentoria de carreira?", "nbs"],
  ["qual o nbs pra autoescola e habilitacao?", "nbs"],
  ["vc sabe o nbs de curso de idioma?", "nbs"],
  ["qual nbs para reforco escolar?", "nbs"],
  ["nbs de aula de danca forro?", "nbs"],
  ["qual o nbs para curso livre de desenho?", "nbs"],
  ["qual o nbs para sessao de fisioterapia?", "nbs"],
  ["nbs de atendimento com dentista?", "nbs"],
  ["qual nbs para terapia com psicologo?", "nbs"],
  ["me diz o nbs de consulta com nutricionista?", "nbs"],
  ["qual o nbs pra sessao de massoterapia?", "nbs"],
  ["nbs para sessao de acupuntura?", "nbs"],
  ["qual nbs de teleconsulta de saude?", "nbs"],
  ["nbs para atendimento odontologico?", "nbs"],
  ["qual o nbs pra sessao de quiropraxia?", "nbs"],
  ["pfv me fala o nbs de atendimento terapeutico?", "nbs"],
  ["qual o nbs para manutencao de ar condicionado?", "nbs"],
  ["nbs de servico de eletricista residencial?", "nbs"],
  ["qual nbs pra encanador e reparo hidraulico?", "nbs"],
  ["me diz o nbs para chaveiro de madrugada?", "nbs"],
  ["qual o nbs para marcenaria sob medida?", "nbs"],
  ["nbs de serralheria e solda?", "nbs"],
  ["qual nbs pra jardinagem e poda?", "nbs"],
  ["nbs para faxina residencial?", "nbs"],
  ["qual o nbs de dedetizacao?", "nbs"],
  ["me fala o nbs para lavanderia de roupa?", "nbs"],
  ["qual nbs para instalacao de cortina?", "nbs"],
  ["ql o nbs pra reparo de telhado?", "nbs"],
  ["qual o nbs para hospedagem em hotel?", "nbs"],
  ["nbs de diaria em pousada?", "nbs"],
  ["qual nbs pra passeio guiado?", "nbs"],
  ["me diz o nbs de servico de guia turistico?", "nbs"],
  ["qual o nbs para transporte de pessoas em van escolar?", "nbs"],
  ["nbs para transfer de aeroporto?", "nbs"],
  ["qual nbs pra agencia de viagem e roteiro?", "nbs"],
  ["nbs de servico de mototaxi?", "nbs"],
  ["qual o nbs para fretamento de van para evento?", "nbs"],
  ["me fala o nbs de passeio de barco?", "nbs"],
  ["qual o nbs para programacao de computadores?", "nbs"],
  ["nbs de suporte tecnico para pc?", "nbs"],
  ["qual nbs pra assinatura de saas?", "nbs"],
  ["me diz o nbs de licenciamento de programa?", "nbs"],
  ["qual o nbs para desenvolvimento de app?", "nbs"],
  ["nbs de criacao de site?", "nbs"],
  ["qual nbs pra backup em nuvem?", "nbs"],
  ["nbs de configuracao de rede?", "nbs"],
  ["qual o nbs para servico de helpdesk?", "nbs"],
  ["me fala o nbs de manutencao de computador?", "nbs"],
  ["q o nbs pra webdesign e layout?", "nbs"],
  ["qual nbs para aula de informatica e digitacao?", "nbs"],
  ["qual o nbs para servico de assessoria administrativa?", "nbs"],
  ["nbs de parecer juridico?", "nbs"],
  ["qual nbs pra pericia tecnica?", "nbs"],
  ["me diz o nbs de auditoria contabil?", "nbs"],
  ["qual o nbs para traducao juramentada?", "nbs"],
  ["nbs de servico de design grafico?", "nbs"],
  ["qual nbs pra marketing e publicidade?", "nbs"],
  ["me fala o nbs de fotografia de evento?", "nbs"],
  ["nbs para assessoria de imprensa?", "nbs"],
  ["qual o nbs pra mentoria de negocio?", "nbs"],
  ["qual atividade e o cnae para aula de yoga?", "nbs"],
  ["me diz o cnae e o nbs para curso de idioma?", "nbs"],
  ["qual o nbs e a atividade para suporte tecnico?", "nbs"],
  ["nbs para tomador de servico de limpeza?", "nbs"],
  ["qual o nbs na lista de servicos da lc 116 para hospedagem?", "nbs"],
  ["me fala o nbs de prestacao de servico de jardinagem?", "nbs"],
  ["qual iss e nbs para aula de danca?", "nbs"],
  ["nbs para atividade de fotografia?", "nbs"],
  ["qual cnae usar pra servico de lavanderia?", "nbs"],
  ["me diz a atividade e o nbs para passeio turistico?", "nbs"],
  ["oi, qual q o nbs pra aula de yoga pfv?", "nbs"],
  ["e ai, me fala o nbs de curso de violao rapidinho?", "nbs"],
  ["mano, q nbs cai pra faxina e diaria?", "nbs"],
  ["qual o nbs pra programasao de computador?", "nbs"],
  ["nbs p aula d ingles com typo?", "nbs"],
  ["pelo amor, me diz o nbs de suporte tecnco?", "nbs"],
  ["qual o ncm de parafuso sextavado?", "ncm"],
  ["ncm para cadeira de madeira?", "ncm"],
  ["qual ncm de camiseta de algodao?", "ncm"],
  ["me diz o ncm do queijo minas?", "ncm"],
  ["ncm de banana prata?", "ncm"],
  ["qual o ncm para medicamento generico?", "ncm"],
  ["quanto fica 2000 reais no nbs 123456789?", "calculo"],
  ["quanto vou pagar de ibs e cbs em 5000 no nbs 987654321?", "calculo"],
  ["calcula pra mim 1500 reais no codigo 123456789?", "calculo"],
  ["quanto da 3000 no nbs 111222333 com iss?", "calculo"],
  ["o que e iss?", "conceito"],
  ["o que significa cnae?", "conceito"],
  ["me explica o que e nbs?", "conceito"],
  ["qual melhor anexo iii ou v?", "comparativo"],
  ["vale a pena ir pro convencional ou hibrido?", "comparativo"],
]
describe('varredura vocab — nbs', () => {
  it('100 casos roteiam como esperado', () => {
    const erros: string[] = []
    for (const [msg, esperado] of CASOS) {
      let obtido: string
      try { obtido = detectarIntencaoChat(msg).intencao } catch (e) { obtido = 'ERRO' }
      if (obtido !== esperado) erros.push(`${msg} → ${obtido} (esperado ${esperado})`)
    }
    expect(erros).toEqual([])
  })
})
