import { describe, expect, it } from 'vitest'
import { detectarIntencaoChat } from '@/domain/services/detector-chat'
const CASOS: Array<[string, string]> = [
  ["tem algum XML de algum cliente?", "dados"],
  ["tem XML importado em março/2026?", "dados"],
  ["quantos XML importei em janeiro/2026?", "dados"],
  ["quais XML entraram de 01/01/2026 a 31/03/2026?", "dados"],
  ["tem XML da Padaria Pão Dourado?", "dados"],
  ["mostra os XML de fevereiro/2026?", "dados"],
  ["lista os XML importados em 2026?", "dados"],
  ["quais notas fiscais entraram em março/2026?", "dados"],
  ["tem nota fiscal com CFOP 5102?", "dados"],
  ["quais NF-e comprei de 01/01/2026 a 31/03/2026?", "dados"],
  ["qual fornecedor me dá mais crédito?", "dados"],
  ["qual fornecedor me da mais credito em 2026?", "dados"],
  ["quais fornecedores me dão mais crédito em março/2026?", "dados"],
  ["top fornecedores por crédito em janeiro/2026?", "dados"],
  ["ranking de fornecedores por crédito?", "dados"],
  ["que fornecedor gera mais crédito nas notas?", "dados"],
  ["qual loja que me dá mais crédito?", "dados"],
  ["quais lojas que geraram mais crédito?", "dados"],
  ["de qual fornecedor mais comprei em fevereiro/2026?", "dados"],
  ["qual fornecedor gerou mais crédito de 01/01/2026 a 31/03/2026?", "dados"],
  ["top 5 fornecedores em março/2026?", "dados"],
  ["ranking de fornecedores que mais venderam em 2026?", "dados"],
  ["qual produto gera mais débito?", "dados"],
  ["qual produto gera mais credito em março/2026?", "dados"],
  ["quais produtos geraram mais crédito em janeiro/2026?", "dados"],
  ["quais produtos geraram mais débito de 01/01/2026 a 31/03/2026?", "dados"],
  ["que produto mais gera crédito nas notas?", "dados"],
  ["qual produto que mais comprei em fevereiro/2026?", "dados"],
  ["qual produto que mais vendi em março/2026?", "dados"],
  ["produtos que mais geraram débito em 2026?", "dados"],
  ["que produto gera mais débito no XML?", "dados"],
  ["qual produto me dá mais crédito nas notas fiscais?", "dados"],
  ["produtos vendidos que geraram mais crédito?", "dados"],
  ["produtos comprados que geraram mais débito?", "dados"],
  ["existe produto diferido nas notas?", "dados"],
  ["tem produto diferido no XML de março/2026?", "dados"],
  ["quais produtos diferidos entraram em janeiro/2026?", "dados"],
  ["lista os produtos diferidos de fevereiro/2026?", "dados"],
  ["tem diferimento nas notas fiscais de 2026?", "dados"],
  ["quais reduções tem nas notas?", "dados"],
  ["quais reducoes aparecem no XML em março/2026?", "dados"],
  ["tem redução nas notas de fevereiro/2026?", "dados"],
  ["mostra a redução nas notas de janeiro/2026?", "dados"],
  ["quais produtos com redução nas notas em 2026?", "dados"],
  ["tem produto com diferimento em março/2026?", "dados"],
  ["quais notas fiscais têm produto diferido?", "dados"],
  ["top 5 produtos vendidos em janeiro/2026?", "dados"],
  ["top 10 produtos vendidos de 01/01/2026 a 31/03/2026?", "dados"],
  ["top 3 produtos comprados em fevereiro/2026?", "dados"],
  ["ranking dos produtos mais vendidos em março/2026?", "dados"],
  ["ranking de produtos comprados em 2026?", "dados"],
  ["lista os produtos vendidos em março/2026?", "dados"],
  ["lista os produtos comprados de 01/01/2026 a 31/03/2026?", "dados"],
  ["quais os produtos mais vendidos em fevereiro/2026?", "dados"],
  ["quais os produtos mais comprados em janeiro/2026?", "dados"],
  ["mostra os produtos mais vendidos em março/2026?", "dados"],
  ["lista os produtos desse cliente em março/2026?", "dados"],
  ["quais produtos desse cliente venderam mais em fevereiro/2026?", "dados"],
  ["top produtos desse cliente em janeiro/2026?", "dados"],
  ["ranking dos mais vendidos no XML?", "dados"],
  ["quais top produtos desse cliente em março/2026?", "dados"],
  ["quanto comprei em janeiro/2026?", "dados"],
  ["quanto vendi em fevereiro/2026?", "dados"],
  ["quanto comprei de 01/01/2026 a 31/03/2026?", "dados"],
  ["quanto vendi de 01/01/2026 a 31/03/2026?", "dados"],
  ["quanto comprei da Padaria Pão Dourado em março/2026?", "dados"],
  ["quanto vendi em março/2026 no XML?", "dados"],
  ["qual o total de entradas e saídas em janeiro/2026?", "dados"],
  ["mostra entradas e saídas de fevereiro/2026?", "dados"],
  ["quanto comprei com CFOP 5102 em março/2026?", "dados"],
  ["quanto vendi com CFOP 5102 de 01/01/2026 a 31/03/2026?", "dados"],
  ["quanto comprei de produtos diferidos em 2026?", "dados"],
  ["quanto vendi de produtos com redução em março/2026?", "dados"],
  ["quais filtros posso usar nos dados?", "dados"],
  ["que filtros existem para o XML?", "dados"],
  ["posso filtrar por período nas notas fiscais?", "dados"],
  ["quais produtos da Padaria Pão Dourado estão no XML?", "dados"],
  ["lista os produtos da Padaria Pão Dourado em março/2026?", "dados"],
  ["quais produtos do cliente Padaria Pão Dourado venderam mais?", "dados"],
  ["top produtos da Padaria Pão Dourado em fevereiro/2026?", "dados"],
  ["ranking de fornecedores da Padaria Pão Dourado?", "dados"],
  ["notas fiscais com CFOP 5102 em março/2026?", "dados"],
  ["quais produtos nas notas fiscais com CFOP 5102?", "dados"],
  ["lista as notas com CFOP 5102 de janeiro/2026?", "dados"],
  ["qual produto comprou de simples em março/2026?", "dados"],
  ["quais meus clientes?", "clientes"],
  ["lista meus clientes cadastrados?", "clientes"],
  ["quantos clientes tenho cadastrados?", "clientes"],
  ["quais empresas tenho cadastradas?", "clientes"],
  ["tem algum cliente novo cadastrado?", "clientes"],
  ["mostra minha lista de clientes?", "clientes"],
  ["que empresas estão cadastradas?", "clientes"],
  ["tem algum ncm de banana?", "ncm"],
  ["qual ncm da banana nanica?", "ncm"],
  ["qual ncm para queijo minas frescal?", "ncm"],
  ["tem algum ncm para carne bovina resfriada?", "ncm"],
  ["qual ncm classifica o medicamento generico?", "ncm"],
  ["o que é diferimento?", "conceito"],
  ["o que significa credito presumido?", "conceito"],
  ["me explica o que é debito fiscal?", "conceito"],
]
describe('varredura vocab — dados', () => {
  it('100 casos roteiam como esperado', () => {
    const erros: string[] = []
    for (const [msg, esperado] of CASOS) {
      let obtido: string
      try { obtido = detectarIntencaoChat(msg).intencao } catch (e) { obtido = 'ERRO' }
      if (obtido !== esperado) erros.push(`${msg} → ${obtido} (esperado ${esperado})`)
    }
    expect(erros).toEqual([])
  })
})
