/**
 * Vocabulário fiscal da Aurum AI — sinônimos, radicais e sinais por capítulo.
 *
 * Papel: dar "contexto de entendimento maior" ao RAG. O usuário digita com
 * palavras do dia a dia ("boi", "celular", "camiseta"); a nomenclatura oficial
 * usa vocabulário técnico ("bovino", "telefone", "camisa"). Sem esta ponte, o
 * RAG lexical nunca matcha e a IA responde NÃO SEI para tudo.
 *
 * Regras:
 * - Chave e valor já normalizados (sem acento, minúsculas).
 * - O valor deve existir LITERALMENTE no texto oficial (ou ser radical comum
 *   às flexões: `bovin` casa com bovino/bovina/bovinos via substring).
 * - A expansão só ADICIONA consultas — a prova continua sendo o match na base
 *   oficial + validação pelo resolvedor (nenhum NCM é inventado).
 */

/** Dia a dia → vocabulário da nomenclatura (radical oficial). */
export const SINONIMOS_FISCAIS: Record<string, string> = {
  // --- pecuária / agro (legado, preservado) ---
  boi: 'bovin',
  vaca: 'bovin',
  novilho: 'bovin',
  novilha: 'bovin',
  bezerro: 'bovin',
  gado: 'bovin',
  nelore: 'bovin',
  zebu: 'bovin',
  touro: 'bovin',
  bezerra: 'bovin',
  holandesa: 'bovin',
  holandes: 'bovin',
  brahman: 'bovin',
  gir: 'bovin',
  girolando: 'bovin',
  jersey: 'bovin',
  bufalo: 'bufalo',
  porco: 'suin',
  porca: 'suin',
  leitao: 'suin',
  suino: 'suin',
  frango: 'ave',
  galinha: 'galinha',
  galo: 'ave',
  franga: 'galinha',
  pintinho: 'ave',
  ave: 'ave',
  carcaca: 'carcaca',
  carcacas: 'carcaca',
  // --- estado do animal / corte / conservação (funil rigoroso 01×02×03) ---
  // Valores são radicais presentes LITERALMENTE no oficial ("congeladas",
  // "refrigeradas", "frescas", "cortadas", "desossadas", "pedacos").
  // Sem isto, o AND estrito quebra no gênero ("congelada" ∉ "congelados").
  congelada: 'congelad',
  congelado: 'congelad',
  congeladas: 'congelad',
  congelados: 'congelad',
  refrigerada: 'refrigerad',
  refrigerado: 'refrigerad',
  refrigeradas: 'refrigerad',
  refrigerados: 'refrigerad',
  resfriada: 'refrigerad',
  resfriado: 'refrigerad',
  resfriadas: 'refrigerad',
  resfriados: 'refrigerad',
  fresca: 'fresc',
  fresco: 'fresc',
  frescas: 'fresc',
  frescos: 'fresc',
  cortada: 'cortad',
  cortado: 'cortad',
  cortadas: 'cortad',
  cortados: 'cortad',
  desossada: 'desossad',
  desossado: 'desossad',
  desossadas: 'desossad',
  desossados: 'desossad',
  pedaco: 'pedaco',
  pedacos: 'pedaco',
  miudezas: 'miudeza',
  viva: 'vivo',
  vivas: 'vivo',
  vivos: 'vivo',
  milho: 'milho',
  semente: 'semente',
  sementes: 'semente',
  plantio: 'semeadura',
  plantar: 'semeadura',
  semeadura: 'semeadura',
  sementeira: 'semente',
  grao: 'grao',
  graos: 'grao',
  racao: 'alimentacao',
  pet: 'alimentacao',
  food: 'alimentacao',
  petfood: 'alimentacao',
  cao: 'caes',
  caes: 'caes',
  cachorro: 'caes',
  gato: 'gatos',
  gatos: 'gatos',
  sal: 'sal',
  arroz: 'arroz',
  feijao: 'feijao',
  trigo: 'trigo',
  soja: 'soja',
  cafe: 'cafe',
  acucar: 'acucar',
  queijo: 'queijo',
  // --- nomes populares de queijo (ausentes na TEC — pool p/ o RAG; o pin
  // exato vive no dicionário comercial). `coalho`/`prato`/`minas` sozinhos
  // NÃO entram: também são enzima, louça e estado.
  parmesao: 'queijo',
  parmeggiano: 'queijo',
  provolone: 'queijo',
  gorgonzola: 'queijo',
  brie: 'queijo',
  camembert: 'queijo',
  cottage: 'queijo',
  ricota: 'queijo',
  polenguinho: 'queijo',
  minas: 'queijo',
  // --- carnes e embutidos (nomes populares ∉ TEC; valor = palavra oficial) ---
  presunto: 'suina',
  bacon: 'suina',
  charque: 'bovina',
  mortadela: 'enchidos',
  linguica: 'enchidos',
  salsicha: 'enchidos',
  paio: 'enchidos',
  salame: 'enchidos',
  galeto: 'ave',
  mussarela: 'mozarela',
  mucarela: 'mozarela',
  musarela: 'mozarela',
  mozarela: 'mozarela',
  leite: 'leite',
  remedio: 'medicamento',
  antibiotico: 'medicamento',
  seringa: 'seringa',
  protese: 'protese',
  // --- carnes / aves / peixes ---
  carne: 'carne',
  picanha: 'carne',
  costela: 'carne',
  lombo: 'lombo',
  peito: 'peito',
  coxa: 'coxa',
  asa: 'asa',
  peixe: 'peixe',
  salmao: 'salmao',
  tilapia: 'tilapia',
  camarao: 'camarao',
  bacalhau: 'bacalhau',
  atum: 'atum',
  sardinha: 'sardinha',
  ovo: 'ovo',
  ovos: 'ovo',
  // --- hortifrúti / alimentos ---
  tomate: 'tomate',
  batata: 'batata',
  cebola: 'cebola',
  alho: 'alho',
  cenoura: 'cenoura',
  alface: 'alface',
  banana: 'banana',
  maca: 'maca',
  laranja: 'laranja',
  uva: 'uva',
  manga: 'manga',
  melao: 'melao',
  melancia: 'melancia',
  morango: 'morango',
  abacaxi: 'abacaxi',
  limao: 'limao',
  mamao: 'mamao',
  // --- cítricos: o oficial usa o plural literal ("Mandarinas (incluindo as
  // tangerinas...)") — a expansão usa o literal para não quebrar o AND ---
  tangerina: 'mandarinas',
  tangerinas: 'mandarinas',
  mandarina: 'mandarinas',
  mexerica: 'mandarinas',
  mexericas: 'mandarinas',
  bergamota: 'mandarinas',
  bergamotas: 'mandarinas',
  ponkan: 'mandarinas',
  satsuma: 'mandarinas',
  satsumas: 'mandarinas',
  clementina: 'clementinas',
  clementinas: 'clementinas',
  farinha: 'farinha',
  macarrao: 'massa',
  miojo: 'massa',
  pao: 'pao',
  bolo: 'pastelaria',
  biscoito: 'bolacha',
  bolacha: 'bolacha',
  chocolate: 'chocolate',
  sorvete: 'sorvete',
  iogurte: 'iogurte',
  manteiga: 'manteiga',
  margarina: 'margarina',
  oleo: 'oleo',
  azeite: 'azeite',
  vinagre: 'vinagre',
  mel: 'mel',
  geleia: 'geleia',
  suco: 'suco',
  refrigerante: 'bebida',
  cerveja: 'cerveja',
  vinho: 'vinho',
  cachaça: 'cachaca',
  cachaca: 'cachaca',
  whisky: 'whisky',
  vodka: 'vodka',
  // --- vestuário / calçados / têxtil ---
  camiseta: 'camisa',
  camisa: 'camisa',
  camisete: 'camisa',
  blusa: 'blusa',
  calca: 'calca',
  calça: 'calca',
  jeans: 'jeans',
  bermuda: 'bermuda',
  short: 'short',
  vestido: 'vestido',
  saia: 'saia',
  terno: 'terno',
  paleto: 'paleto',
  gravata: 'gravata',
  cueca: 'cueca',
  calcinha: 'calcinha',
  sutia: 'sutia',
  meia: 'meia',
  meias: 'meia',
  sapato: 'calcado',
  tenis: 'calcado',
  chinelo: 'chinelo',
  sandalia: 'sandalia',
  bota: 'bota',
  bolsa: 'bolsa',
  mochila: 'mochila',
  mala: 'mala',
  cinto: 'cinto',
  bone: 'bone',
  chapeu: 'chapeu',
  algodao: 'algodao',
  seda: 'seda',
  la: 'la',
  poliester: 'poliester',
  nylon: 'nailon',
  // --- eletrônicos / informática / telefonia ---
  celular: 'telefone',
  smartphone: 'telefone',
  iphone: 'telefone',
  telefone: 'telefone',
  tablet: 'tablet',
  notebook: 'computador',
  laptop: 'computador',
  computador: 'computador',
  pc: 'computador',
  monitor: 'monitor',
  teclado: 'teclado',
  mouse: 'mouse',
  impressora: 'impressora',
  tv: 'televisao',
  televisao: 'televisao',
  smartv: 'televisao',
  radio: 'radio',
  caixa: 'caixa',
  som: 'audio',
  fone: 'fone',
  headphone: 'fone',
  headset: 'fone',
  carregador: 'carregador',
  bateria: 'acumuladores',
  pilha: 'pilha',
  lampada: 'lampada',
  led: 'led',
  geladeira: 'refrigerador',
  refrigerador: 'refrigerador',
  freezer: 'congelador',
  fogao: 'fogao',
  forno: 'forno',
  microondas: 'microondas',
  ar: 'condicionador',
  ventilador: 'ventilador',
  chuveiro: 'chuveiro',
  maquina: 'maquina',
  motor: 'motor',
  bomba: 'bomba',
  trator: 'trator',
  colheitadeira: 'colheitadeira',
  // --- farmácia / cosméticos / higiene ---
  perfume: 'perfumaria',
  colonia: 'perfumaria',
  shampoo: 'xampus',
  condicionador: 'condicionador',
  sabonete: 'saboes',
  sabao: 'saboes',
  detergente: 'detergente',
  pasta: 'pasta',
  escova: 'escova',
  fralda: 'fralda',
  absorvente: 'absorvente',
  creme: 'creme',
  protetor: 'protetor',
  maquiagem: 'maquilhagem',
  batom: 'batom',
  esmalte: 'esmalte',
  // --- móveis / casa / construção ---
  sofa: 'assento',
  cadeira: 'assento',
  mesa: 'mesa',
  cama: 'cama',
  guarda: 'guardaroupa',
  armario: 'armario',
  estante: 'estante',
  colchao: 'colchao',
  travesseiro: 'travesseiro',
  panela: 'panela',
  frigideira: 'frigideira',
  talher: 'talher',
  copo: 'copo',
  prato: 'prato',
  tijolo: 'tijolo',
  cimento: 'cimento',
  tinta: 'tinta',
  verniz: 'verniz',
  martelo: 'ferramenta',
  chave: 'ferramenta',
  parafuso: 'parafuso',
  prego: 'prego',
  // --- veículos / autopeças ---
  carro: 'veiculo',
  moto: 'motocicleta',
  caminhao: 'caminhao',
  onibus: 'onibus',
  bicicleta: 'bicicleta',
  pneu: 'pneumatico',
  motorcarro: 'motor',
  retrovisor: 'retrovisor',
  farol: 'farois',
  // --- papelaria / diversos ---
  caneta: 'caneta',
  lapis: 'lapis',
  caderno: 'caderno',
  livro: 'livro',
  brinquedo: 'brinquedo',
  boneca: 'boneca',
  bola: 'bola',
  raquete: 'raquete',
  // --- base de conhecimento expandida (comum + incomum) ---
  // Dia a dia → radical oficial TEC (valor existe LITERALMENTE no oficial
  // após normalizarBusca; a prova continua sendo o match + resolvedor).
  airfryer: 'grelha',
  fritadeira: 'grelha',
  sanduicheira: 'grelha',
  torradeira: 'torrada',
  alexa: 'altifalante',
  echo: 'altifalante',
  soundbar: 'altifalante',
  jbl: 'altifalante',
  kindle: 'leitor',
  ereader: 'leitor',
  smartwatch: 'relogio',
  relogio: 'relogio',
  drone: 'aeronave',
  roteador: 'transmissao',
  router: 'transmissao',
  webcam: 'camera',
  camera: 'camera',
  gopro: 'camera',
  videogame: 'console',
  playstation: 'console',
  xbox: 'console',
  nintendo: 'console',
  joystick: 'console',
  // Marcas / siglas / inglês comercial → hiperônimo oficial.
  samsung: 'telefone',
  motorola: 'telefone',
  xiaomi: 'telefone',
  philips: 'televisao',
  sony: 'televisao',
  nescau: 'cacau',
  danone: 'iogurte',
  nestle: 'chocolate',
  nike: 'calcado',
  adidas: 'calcado',
  whey: 'suplemento',
  creatina: 'suplemento',
  skincare: 'creme',
  // Vestuário expandido — dia a dia → oficial.
  cropped: 'blusa',
  legging: 'calca',
  moletom: 'sueter',
  sueter: 'sueter',
  cardiga: 'cardiga',
  regata: 'camiseta',
  babylook: 'camiseta',
  jaqueta: 'casaco',
  casaco: 'casaco',
  sobretudo: 'sobretudo',
  biquini: 'banho',
  sunga: 'banho',
  lingerie: 'calcinha',
  pijama: 'pijama',
  roupao: 'roupao',
  // Alimentos / bebidas — nomes de mercado → oficial.
  tapioca: 'fecula',
  fecula: 'fecula',
  polvilho: 'fecula',
  granola: 'cereal',
  doce: 'confeitaria',
  bala: 'confeitaria',
  chiclete: 'goma',
  energetico: 'bebida',
  isotonico: 'bebida',
  gin: 'aguardente',
  rum: 'aguardente',
  tequila: 'aguardente',
  licor: 'licor',
  espumante: 'vinho',
  // Casa / ferramentas / autopeças.
  aspirador: 'aspirador',
  liquidificador: 'liquidificador',
  batedeira: 'batedeira',
  cafeteira: 'cafeteira',
  furadeira: 'furar',
  parafusadeira: 'parafuso',
  lixadeira: 'ferramenta',
  alicate: 'alicate',
  pastilha: 'pastilha',
  freio: 'freio',
  amortecedor: 'amortecedor',
  embreagem: 'embreagem',
  correia: 'correia',
  filtro: 'filtrar',
  // Erros comuns de digitação (sem acento, já normalizados).
  parmezao: 'queijo',
  muzzarela: 'mozarela',
  notbook: 'computador',
  notebbok: 'computador',
  celula: 'telefone',
  smartfone: 'telefone',
  television: 'televisao',
  teve: 'televisao',
  xocolate: 'chocolate',
  cerjeva: 'cerveja',
  serueja: 'cerveja',
  linguissa: 'enchidos',
  salsixa: 'enchidos',
  presuntoo: 'suina',
  camizeta: 'camisa',
  tennis: 'calcado',
  fraldaa: 'fralda',
  // --- 33+ novos segmentos: autopeças / metal / têxtil / construção ---
  // Valores existem LITERALMENTE no oficial (ou radical comum às flexões).
  // (`farol/bateria/filtro/shampoo/sabao/sabonete/pneu` atualizados in-place
  // acima para o radical oficial — sem duplicar chaves.)
  dentada: 'sincrona',
  vergalhao: 'nervura',
  fio: 'fios',
  denim: 'indigo',
  tricoline: 'tecido',
  toalha: 'atoalhado',
  lencol: 'cama',
  serrote: 'serra',
  // --- EXPANSÃO MÁXIMA v2: químicos inorgânicos (cap. 28 — valores literais TEC) ---
  acido: 'acido',
  acidos: 'acido',
  sulfurico: 'sulfurico',
  cloridrico: 'cloridrato',
  nitrico: 'nitrico',
  fosforico: 'fosforico',
  soda: 'sodio',
  caustica: 'sodio',
  cal: 'calcio',
  calcario: 'calcio',
  amonia: 'amonio',
  cloro: 'cloro',
  fluor: 'fluor',
  oxigenio: 'oxigenio',
  nitrogenio: 'nitrogenio',
  hidroxido: 'hidroxido',
  oxido: 'oxido',
  sulfato: 'sulfato',
  sulfito: 'sulfito',
  nitrato: 'nitrato',
  nitrito: 'nitrito',
  fosfato: 'fosfato',
  carbonato: 'carbonato',
  bicarbonato: 'carbonato',
  cloreto: 'cloreto',
  hipoclorito: 'hipoclorito',
  peroxido: 'peroxido',
  enxofre: 'enxofre',
  iodo: 'iodo',
  bromo: 'bromo',
  potassio: 'potassio',
  magnesio: 'magnesio',
  aluminio: 'aluminio',
  zinco: 'zinco',
  chumbo: 'chumbo',
  estanho: 'estanho',
  niquel: 'niquel',
  cromo: 'cromo',
  manganes: 'manganes',
  titanio: 'titanio',
  // --- químicos orgânicos (cap. 29) ---
  metanol: 'metanol',
  etanol: 'etanol',
  alcool: 'alcool',
  glicerina: 'glicerol',
  acetona: 'acetona',
  benzeno: 'benzeno',
  tolueno: 'tolueno',
  xileno: 'xileno',
  fenol: 'fenol',
  formol: 'formaldeido',
  ureia: 'ureia',
  anilina: 'anilina',
  etileno: 'etileno',
  propileno: 'propileno',
  butano: 'butano',
  propano: 'propano',
  metano: 'metano',
  acetato: 'acetato',
  citrato: 'citrato',
  lactato: 'lactato',
  benzoato: 'benzoato',
  salicilato: 'salicilato',
  eter: 'eteres',
  cetona: 'cetona',
  aldeido: 'aldeido',
  amina: 'amina',
  amida: 'amida',
  ester: 'esteres',
  // --- farmácia expandida (cap. 30 — dia a dia → oficial) ---
  comprimido: 'comprimido',
  capsula: 'capsula',
  drajea: 'drajea',
  xarope: 'xarope',
  vacina: 'vacina',
  soro: 'soro',
  pomada: 'pomada',
  gel: 'gel',
  spray: 'spray',
  inalador: 'inalacao',
  analgesico: 'analgesico',
  antitermico: 'antipiretico',
  antialergico: 'antialergico',
  antiinflamatorio: 'antiinflamatorio',
  corticoide: 'corticoide',
  insulina: 'insulina',
  dipirona: 'dipirona',
  paracetamol: 'paracetamol',
  ibuprofeno: 'ibuprofeno',
  omeprazol: 'omeprazol',
  losartana: 'losartana',
  atenolol: 'atenolol',
  amoxicilina: 'amoxicilina',
  azitromicina: 'azitromicina',
  suplemento: 'suplemento',
  vitamina: 'vitamina',
  polivitaminico: 'vitamina',
  homeopatico: 'homeopatico',
  fitoterapico: 'fitoterapico',
  contraste: 'contraste',
  curativo: 'curativo',
  esparadrapo: 'esparadrapo',
  gaze: 'gaze',
  agulha: 'agulha',
  cateter: 'cateter',
  sonda: 'sonda',
  stent: 'stent',
  marcapasso: 'marcapasso',
  ortese: 'ortese',
  aparelho: 'aparelho',
  // --- fertilizantes / agroquímicos (cap. 31 + 38) ---
  fertilizante: 'fertilizante',
  adubo: 'adubo',
  npk: 'fertilizante',
  fosfatado: 'fosfatado',
  nitrogenado: 'azoto',
  herbicida: 'herbicida',
  inseticida: 'inseticida',
  fungicida: 'fungicida',
  pesticida: 'pesticida',
  agrotoxico: 'pesticida',
  defensivo: 'defensivo',
  roundup: 'herbicida',
  glifosato: 'glifosato',
  // --- tintas / cosméticos / sabões (cap. 32-34) ---
  thinner: 'diluente',
  solvente: 'solvente',
  pigmento: 'pigmento',
  corante: 'corante',
  resina: 'resina',
  desodorante: 'desodorizante',
  hidratante: 'hidratante',
  base: 'base',
  rimel: 'rimel',
  delineador: 'delineador',
  desinfetante: 'desinfetante',
  amaciante: 'amaciante',
  alvejante: 'branqueador',
  cera: 'cera',
  vela: 'vela',
  // --- plásticos / borracha (cap. 39-40) ---
  plastico: 'plastico',
  pvc: 'cloreto',
  polietileno: 'etileno',
  polipropileno: 'propileno',
  poliestireno: 'estireno',
  acrilico: 'acrilico',
  teflon: 'tetrafluoretileno',
  silicone: 'silicone',
  isopor: 'estireno',
  sacola: 'saco',
  embalagem: 'embalagem',
  garrafa: 'garrafa',
  pote: 'pote',
  tampa: 'tampa',
  cano: 'tubo',
  tubo: 'tubo',
  mangueira: 'tubo',
  borracha: 'borracha',
  latex: 'latex',
  camara: 'camara',
  // --- couro / peles (cap. 41-43) ---
  couro: 'couro',
  camurca: 'camurca',
  napa: 'couro',
  sola: 'sola',
  selaria: 'selaria',
  pele: 'pele',
  // --- madeira / cortiça / papel (cap. 44-48) ---
  madeira: 'madeira',
  tabua: 'tabua',
  viga: 'viga',
  caibro: 'caibro',
  compensado: 'compensado',
  mdf: 'fibra',
  mdp: 'particula',
  osb: 'particula',
  laminado: 'folha',
  palete: 'palete',
  lenha: 'lenha',
  carvao: 'carvao',
  cortica: 'cortica',
  rolha: 'rolha',
  papel: 'papel',
  papelao: 'papelao',
  cartolina: 'cartolina',
  guardanapo: 'guardanapo',
  revista: 'revista',
  jornal: 'jornal',
  envelope: 'envelope',
  etiqueta: 'etiqueta',
  // --- têxtil expandido (cap. 50-63) ---
  linha: 'linha',
  linho: 'linho',
  juta: 'juta',
  sisal: 'sisal',
  viscose: 'viscose',
  elastano: 'elastano',
  lycra: 'elastano',
  renda: 'renda',
  bordado: 'bordado',
  veludo: 'veludo',
  cetim: 'cetim',
  sarja: 'sarja',
  flanela: 'flanela',
  malha: 'malha',
  trico: 'malha',
  croche: 'croche',
  tapete: 'tapete',
  carpete: 'carpete',
  cortina: 'cortina',
  edredom: 'edredom',
  cobertor: 'cobertor',
  fronha: 'fronha',
  rede: 'rede',
  // --- calçados / chapéus / guarda-chuvas (cap. 64-66) ---
  calcado: 'calcado',
  sapatenis: 'calcado',
  mocassim: 'mocassim',
  scarpin: 'scarpin',
  coturno: 'coturno',
  galocha: 'calcado',
  palmilha: 'palmilha',
  cadarco: 'atacador',
  viseira: 'viseira',
  capacete: 'capacete',
  sombrinha: 'sombrinha',
  // --- pedra / cerâmica / vidro (cap. 68-70) ---
  marmore: 'marmore',
  granito: 'granito',
  ardosa: 'ardosia',
  gesso: 'gesso',
  amianto: 'amianto',
  lixa: 'lixa',
  ceramica: 'ceramica',
  porcelana: 'porcelana',
  azulejo: 'azulejo',
  louca: 'louca',
  vaso: 'vaso',
  telha: 'telha',
  vidro: 'vidro',
  cristal: 'cristal',
  espelho: 'espelho',
  // --- metais expandidos (cap. 72-83) ---
  aco: 'aco',
  inox: 'inoxidavel',
  ferro: 'ferro',
  fundido: 'fundido',
  chapa: 'chapa',
  barra: 'barra',
  perfil: 'perfil',
  cantoneira: 'cantoneira',
  trilho: 'trilho',
  cobre: 'cobre',
  latao: 'latao',
  bronze: 'bronze',
  ferramenta: 'ferramenta',
  faca: 'faca',
  tesoura: 'tesoura',
  fechadura: 'fechadura',
  dobradica: 'dobradica',
  cadeado: 'cadeado',
  // --- máquinas (cap. 84 — dia a dia → oficial) ---
  escavadeira: 'escavadeira',
  empilhadeira: 'empilhadeira',
  guindaste: 'guindaste',
  compressor: 'compressor',
  valvula: 'valvula',
  rolamento: 'rolamento',
  engrenagem: 'engrenagem',
  torno: 'torno',
  fresa: 'fresa',
  prensa: 'prensa',
  serra: 'serra',
  esmerilhadeira: 'esmeril',
  motoserra: 'serra',
  rocadeira: 'rocadeira',
  gerador: 'gerador',
  transformador: 'transformador',
  caldeira: 'caldeira',
  estufa: 'estufa',
  exaustor: 'exaustor',
  coifa: 'coifa',
  bebedouro: 'bebedouro',
  balanca: 'balanca',
  elevador: 'elevador',
  esteira: 'esteira',
  // --- elétricos expandidos (cap. 85) ---
  cabo: 'cabo',
  tomada: 'tomada',
  interruptor: 'interruptor',
  disjuntor: 'disjuntor',
  fusivel: 'fusivel',
  quadro: 'quadro',
  luminaria: 'luminaria',
  refletor: 'refletor',
  poste: 'poste',
  nobreak: 'alimentacao',
  estabilizador: 'estabilizador',
  inversor: 'inversor',
  alto: 'altifalante',
  microfone: 'microfone',
  interfone: 'interfone',
  antena: 'antena',
  modem: 'modem',
  switch: 'comutacao',
  servidor: 'servidor',
  hd: 'disco',
  ssd: 'disco',
  pendrive: 'memoria',
  cartao: 'cartao',
  scanner: 'scanner',
  projetor: 'projetor',
  // --- veículos expandidos (cap. 86-89) ---
  locomotiva: 'locomotiva',
  vagao: 'vagao',
  van: 'veiculo',
  pickup: 'veiculo',
  suv: 'veiculo',
  reboque: 'reboque',
  carretinha: 'reboque',
  scooter: 'motocicleta',
  quadriciclo: 'quadriciclo',
  peca: 'peca',
  cambio: 'cambio',
  radiador: 'radiador',
  escapamento: 'escapamento',
  catalisador: 'catalisador',
  airbag: 'airbag',
  banco: 'banco',
  painel: 'painel',
  parabrisa: 'parabrisa',
  limpador: 'limpador',
  roda: 'roda',
  calota: 'calota',
  barco: 'barco',
  lancha: 'lancha',
  jetski: 'moto',
  canoa: 'canoa',
  aviao: 'aviao',
  helicoptero: 'helicoptero',
  // --- instrumentos / ótica / médico (cap. 90-92) ---
  oculos: 'oculos',
  lente: 'lente',
  armacao: 'armacao',
  termometro: 'termometro',
  esfigmomanometro: 'pressao',
  estetoscopio: 'estetoscopio',
  ultrassom: 'ultrassom',
  raiox: 'radiacao',
  tomografo: 'tomografo',
  microscopio: 'microscopio',
  cronometro: 'cronometro',
  bussola: 'bussola',
  gps: 'navegacao',
  despertador: 'despertador',
  piano: 'piano',
  violao: 'violao',
  guitarra: 'guitarra',
  // --- móveis / brinquedos / diversos (cap. 94-96) ---
  poltrona: 'assento',
  puff: 'assento',
  rack: 'rack',
  criado: 'criado',
  comoda: 'comoda',
  beliche: 'beliche',
  berco: 'berco',
  abajur: 'abajur',
  lustre: 'lustre',
  lego: 'brinquedo',
  barbie: 'boneca',
  pelucia: 'pelucia',
  quebra: 'quebra',
  jogo: 'jogo',
  patinete: 'patinete',
  skate: 'skate',
  patins: 'patins',
  piscina: 'piscina',
  pente: 'pente',
  vassoura: 'vassoura',
  rodo: 'rodo',
  balde: 'balde',
  lixeira: 'lixeira',
  isqueiro: 'isqueiro',
  // --- alimentos expandidos (cap. 02-23) ---
  costelinha: 'costela',
  alcatra: 'carne',
  file: 'file',
  maminha: 'carne',
  cupim: 'carne',
  fraldinha: 'carne',
  contrafile: 'carne',
  coxao: 'carne',
  patinho: 'carne',
  acem: 'carne',
  musculo: 'musculo',
  figado: 'figado',
  coracao: 'coracao',
  dobradinha: 'miudeza',
  mocoto: 'mocoto',
  rabada: 'rabo',
  chester: 'ave',
  peru: 'peru',
  pato: 'pato',
  codorna: 'codorna',
  coelho: 'coelho',
  lula: 'lula',
  polvo: 'polvo',
  mexilhao: 'mexilhao',
  ostra: 'ostra',
  lagosta: 'lagosta',
  caranguejo: 'caranguejo',
  siri: 'siri',
  merluza: 'merluza',
  pescada: 'pescada',
  dourado: 'dourado',
  tucunare: 'peixe',
  pirarucu: 'peixe',
  tambaqui: 'peixe',
  coalhada: 'coalhada',
  nata: 'nata',
  brigadeiro: 'chocolate',
  beijinho: 'confeitaria',
  paçoca: 'amendoim',
  pacoca: 'amendoim',
  pe: 'pe',
  rapadura: 'rapadura',
  aveia: 'aveia',
  cereal: 'cereal',
  cuscuz: 'cuscuz',
  polenta: 'polenta',
  canjica: 'canjica',
  pipoca: 'pipoca',
  amendoim: 'amendoim',
  castanha: 'castanha',
  caju: 'caju',
  noz: 'noz',
  pistache: 'pistache',
  avela: 'avela',
  passas: 'passa',
  damasco: 'damasco',
  ameixa: 'ameixa',
  figo: 'figo',
  tamara: 'tamara',
  goiaba: 'goiaba',
  abacate: 'abacate',
  avocado: 'abacate',
  maracuja: 'maracuja',
  caqui: 'caqui',
  carambola: 'carambola',
  jabuticaba: 'jabuticaba',
  acerola: 'acerola',
  siriguela: 'siriguela',
  graviola: 'graviola',
  atemoia: 'atemoia',
  pitaya: 'pitaya',
  kiwi: 'kiwi',
  pessego: 'pessego',
  nectarina: 'nectarina',
  pera: 'pera',
  cereja: 'cereja',
  framboesa: 'framboesa',
  amora: 'amora',
  mirtilo: 'mirtilo',
  pepino: 'pepino',
  pimentao: 'pimentao',
  quiabo: 'quiabo',
  jilo: 'jilo',
  maxixe: 'maxixe',
  abobora: 'abobora',
  abobrinha: 'abobrinha',
  berinjela: 'berinjela',
  chuchu: 'chuchu',
  vagem: 'vagem',
  ervilha: 'ervilha',
  lentilha: 'lentilha',
  palmito: 'palmito',
  alcachofra: 'alcachofra',
  aspargo: 'aspargo',
  brocolis: 'brocolis',
  couve: 'couve',
  repolho: 'repolho',
  rucula: 'rucula',
  agriao: 'agriao',
  espinafre: 'espinafre',
  oregano: 'oregano',
  manjericao: 'manjericao',
  salsa: 'salsa',
  coentro: 'coentro',
  cebolinha: 'cebolinha',
  alecrim: 'alecrim',
  tomilho: 'tomilho',
  louro: 'louro',
  cominho: 'cominho',
  canela: 'canela',
  cravo: 'cravo',
  gengibre: 'gengibre',
  mascavo: 'acucar',
  demerara: 'acucar',
  adoçante: 'edulcorante',
  adocante: 'edulcorante',
  ketchup: 'ketchup',
  mostarda: 'mostarda',
  maionese: 'maionese',
  shoyu: 'molho',
  dende: 'dende',
  // --- bebidas expandidas ---
  guarana: 'bebida',
  tonic: 'bebida',
  tonica: 'bebida',
  nectar: 'nectar',
  cha: 'cha',
  mate: 'mate',
  terere: 'mate',
  chimarrao: 'mate',
  agua: 'agua',
  chope: 'chope',
  champanhe: 'champanhe',
  sidra: 'sidra',
  sake: 'sake',
  pinga: 'cachaca',
  conhaque: 'conhaque',
  brandy: 'conhaque',
  amarula: 'licor',
  // --- marcas / siglas / inglês comercial (→ hiperônimo oficial) ---
  lg: 'televisao',
  tcl: 'televisao',
  aoc: 'monitor',
  dell: 'computador',
  hp: 'computador',
  lenovo: 'computador',
  asus: 'computador',
  acer: 'computador',
  apple: 'telefone',
  airpods: 'fone',
  canon: 'camera',
  nikon: 'camera',
  fiat: 'veiculo',
  volkswagen: 'veiculo',
  ford: 'veiculo',
  chevrolet: 'veiculo',
  toyota: 'veiculo',
  honda: 'motocicleta',
  yamaha: 'motocicleta',
  tramontina: 'talher',
  havaianas: 'chinelo',
  lacta: 'chocolate',
  garoto: 'chocolate',
  sadia: 'carne',
  seara: 'carne',
  perdigao: 'carne',
  italac: 'leite',
  piracanjuba: 'leite',
  elegê: 'leite',
  elege: 'leite',
  tody: 'cacau',
  sustagen: 'suplemento',
  ensure: 'suplemento',
  neosaldina: 'analgesico',
  tylenol: 'analgesico',
  advil: 'antiinflamatorio',
  usb: 'transmissao',
  hdmi: 'transmissao',
  wifi: 'transmissao',
  bluetooth: 'transmissao',
  lcd: 'cristal',
  '4k': 'televisao',
  smart: 'inteligente',
  pro: 'profissional',
  plus: 'adicao',
  mini: 'pequeno',
  max: 'maximo',
  ultra: 'ultra',
  turbo: 'turbo',
  air: 'ar',
  fit: 'fitness',
  baby: 'infantil',
  kids: 'infantil',
  dog: 'caes',
  cat: 'gatos',
  // --- typos adicionais (normalizados) ---
  parmessao: 'queijo',
  provoloni: 'queijo',
  gorgonsola: 'queijo',
  requeijao: 'requeijao',
  linguisa: 'enchidos',
  salsichao: 'enchidos',
  mortandela: 'enchidos',
  computado: 'computador',
  tecladdo: 'teclado',
  mause: 'mouse',
  monito: 'monitor',
  geladera: 'refrigerador',
  arcondicionado: 'condicionador',
  ventilado: 'ventilador',
  batedera: 'batedeira',
  cafetera: 'cafeteira',
  aspirado: 'aspirador',
  furadera: 'furar',
}

/** Expande um token para o vocabulário oficial (ou `null`). */
export function expandirSinonimoFiscal(token: string): string | null {
  return SINONIMOS_FISCAIS[token] ?? null
}

/**
 * Expansão em lote com cache: mapeia N tokens de uma vez sem re-hash por
 * token. Usado pelo RAG para montar `consultasEfetivas` e pelo seletor IA.
 * Retorna os tokens expandidos (sem duplicatas, ordem estável).
 */
const _cacheExpansaoLote = new Map<string, string[]>()
export function expandirSinonimosTodos(tokens: readonly string[]): string[] {
  const chave = tokens.join('|')
  const hit = _cacheExpansaoLote.get(chave)
  if (hit) return hit
  const out: string[] = []
  const vistos = new Set<string>()
  for (const t of tokens) {
    const e = SINONIMOS_FISCAIS[t] ?? t
    for (const x of [t, e]) {
      if (!vistos.has(x)) {
        vistos.add(x)
        out.push(x)
      }
    }
  }
  if (_cacheExpansaoLote.size > 2000) _cacheExpansaoLote.clear()
  _cacheExpansaoLote.set(chave, out)
  return out
}

/** Quantos sinônimos o vocabulário cobre (auditoria/cobertura). */
export function tamanhoVocabularioFiscal(): number {
  return Object.keys(SINONIMOS_FISCAIS).length
}

/**
 * Radicalização simples pt-BR para o RAG (sem dependências).
 * Remove plurais e sufixos comuns para aproximar "camisetas"→"camiseta",
 * "bovinos"→"bovin", "queijos"→"queij".
 *
 * Com memoização: o RAG chama `radicalizar` O(tokens × docs) vezes por
 * consulta; o cache limita o custo ao vocabulário distinto da sessão.
 */
const _cacheRadical = new Map<string, string>()
export function radicalizar(token: string): string {
  const hit = _cacheRadical.get(token)
  if (hit !== undefined) return hit
  let t = String(token || '').toLowerCase()
  const original = t
  if (t && t.length > 3) {
    // plurais
    if (t.endsWith('oes')) t = t.slice(0, -3) + 'ao'
    else if (t.endsWith('aes')) t = t.slice(0, -3) + 'ao'
    else if (t.endsWith('ais')) t = t.slice(0, -3) + 'al'
    else if (t.endsWith('eis')) t = t.slice(0, -3) + 'el'
    else if (t.endsWith('is')) t = t.slice(0, -2) + 'il'
    else if (t.endsWith('ns')) t = t.slice(0, -2) + 'm'
    else if (t.endsWith('es') && t.length > 4) t = t.slice(0, -2)
    else if (t.endsWith('s') && t.length > 3) t = t.slice(0, -1)
    // diminutivos / aumentativos comuns
    for (const suf of ['zinho', 'zinha', 'inhos', 'inhas', 'eiras', 'eira', 'eiro']) {
      if (t.endsWith(suf) && t.length - suf.length >= 3) {
        t = t.slice(0, -suf.length)
        break
      }
    }
  }
  if (_cacheRadical.size > 5000) _cacheRadical.clear()
  _cacheRadical.set(token, t)
  void original
  return t
}

/** Distância de Levenshtein com teto (para fuzzy barato no RAG). */
export function distanciaLevenshtein(a: string, b: string, teto = 2): number {
  const s = String(a || '')
  const t = String(b || '')
  if (s === t) return 0
  const la = s.length
  const lb = t.length
  if (!la) return lb
  if (!lb) return la
  if (Math.abs(la - lb) > teto) return teto + 1
  let prev = new Array<number>(lb + 1)
  for (let j = 0; j <= lb; j++) prev[j] = j
  for (let i = 1; i <= la; i++) {
    const cur = new Array<number>(lb + 1)
    cur[0] = i
    let minLinha = cur[0]
    for (let j = 1; j <= lb; j++) {
      const custo = s[i - 1] === t[j - 1] ? 0 : 1
      cur[j] = Math.min(prev[j] + 1, cur[j - 1] + 1, prev[j - 1] + custo)
      if (cur[j] < minLinha) minLinha = cur[j]
    }
    if (minLinha > teto) return teto + 1
    prev = cur
  }
  return prev[lb]
}

/**
 * `true` quando o token da consulta casa com o token oficial por alguma via
 * tolerante: substring, radical ou fuzzy (typo).
 *
 * Guarda anti-ruído: substring/radical exigem ≥4 chars nos DOIS lados
 * ("nave" NÃO casa com "ave"; "queijo" casa com "queijos"). Exato (`===`)
 * vale sempre ("sal" casa com "sal"). Fuzzy só para termos ≥5 chars.
 */
export function casaToken(consulta: string, oficial: string): boolean {
  const q = String(consulta || '')
  const o = String(oficial || '')
  if (!q || !o) return false
  if (q === o) return true
  const minLen = Math.min(q.length, o.length)
  // substring só com lastro (evita "de" casar com tudo e "nave" com "ave")
  if (minLen >= 4 && (o.includes(q) || q.includes(o))) return true
  if (q.length < 4 || o.length < 4) return false
  if (radicalizar(q) === radicalizar(o)) return true
  const rQ = radicalizar(q)
  const rO = radicalizar(o)
  if (rQ.length >= 4 && rO.length >= 4 && (rO.includes(rQ) || rQ.includes(rO))) return true
  // typo: 1 edição para termos médios, 2 para longos
  if (q.length >= 5 && o.length >= 5) {
    const teto = q.length >= 8 && o.length >= 8 ? 2 : 1
    if (distanciaLevenshtein(q, o, teto) <= teto) return true
  }
  return false
}
