import type { TabelaAuxiliarSimples } from '../entities'

/**
 * Seeds das tabelas auxiliares (SPEC R9.6).
 * CFOP gerado de bases-fonte/cfop.json em 2026-10-08
 * (619 CFOPs oficiais — cura completa; o que já existia foi mantido).
 * Gravados apenas quando a respectiva store estiver vazia ou por
 * complementação dos códigos faltantes (garantirSementes).
 */

export const SEED_CFOP: TabelaAuxiliarSimples[] = [
  {"codigo":"1101","descricao":"Compra para industrialização ou produção rural","tipo":"Entrada"},
  {"codigo":"1102","descricao":"Compra para comercialização","tipo":"Entrada"},
  {"codigo":"1111","descricao":"Compra para industrialização de mercadoria recebida anteriormente em consignação industrial","tipo":"Entrada"},
  {"codigo":"1113","descricao":"Compra para comercialização, de mercadoria recebida anteriormente em consignação mercantil","tipo":"Entrada"},
  {"codigo":"1116","descricao":"Compra para industrialização ou produção rural originada de encomenda para recebimento futuro","tipo":"Entrada"},
  {"codigo":"1117","descricao":"Compra para comercialização originada de encomenda para recebimento futuro","tipo":"Entrada"},
  {"codigo":"1118","descricao":"Compra de mercadoria para comercialização pelo adquirente originário, entregue pelo vendedor remetente ao destinatário, em venda à ordem","tipo":"Entrada"},
  {"codigo":"1120","descricao":"Compra para industrialização ou produção rural, em venda à ordem, já recebida do vendedor remetente","tipo":"Entrada"},
  {"codigo":"1121","descricao":"Compra para comercialização, em venda à ordem, já recebida do vendedor remetente","tipo":"Entrada"},
  {"codigo":"1122","descricao":"Compra para industrialização em que a mercadoria foi remetida pelo fornecedor ao industrializador sem transitar pelo estabelecimento adquirente","tipo":"Entrada"},
  {"codigo":"1124","descricao":"Industrialização efetuada por outra empresa","tipo":"Entrada"},
  {"codigo":"1125","descricao":"Industrialização efetuada por outra empresa quando a mercadoria remetida para utilização no processo de industrialização não transitou pelo estabelecimento adquirente da mercadoria","tipo":"Entrada"},
  {"codigo":"1126","descricao":"Compra para utilização na prestação de serviço sujeita ao ICMS","tipo":"Entrada"},
  {"codigo":"1128","descricao":"Compra para utilização na prestação de serviço sujeita ao ISSQN","tipo":"Entrada"},
  {"codigo":"1131","descricao":"Entrada de mercadoria, com previsão de posterior ajuste ou fixação de preço, em ato cooperativo","tipo":"Entrada"},
  {"codigo":"1132","descricao":"Fixação de preço de produção do estabelecimento produtor, inclusive quando remetidas anteriormente com previsão de posterior ajuste ou fixação de preço, em ato cooperativo, para comercialização","tipo":"Entrada"},
  {"codigo":"1135","descricao":"Fixação de preço de produção do estabelecimento produtor, inclusive quando remetidas anteriormente com previsão de posterior ajuste ou fixação de preço, em ato cooperativo, para industrialização","tipo":"Entrada"},
  {"codigo":"1151","descricao":"Transferência para industrialização ou produção rural","tipo":"Entrada"},
  {"codigo":"1152","descricao":"Transferência para comercialização","tipo":"Entrada"},
  {"codigo":"1153","descricao":"Transferência de energia elétrica para distribuição","tipo":"Entrada"},
  {"codigo":"1154","descricao":"Transferência para utilização na prestação de serviço","tipo":"Entrada"},
  {"codigo":"1159","descricao":"Entrada decorrente do fornecimento de produto ou mercadoria em ato cooperativo","tipo":"Entrada"},
  {"codigo":"1201","descricao":"Devolução de venda de produção do estabelecimento","tipo":"Entrada"},
  {"codigo":"1202","descricao":"Devolução de venda de mercadoria adquirida ou recebida de terceiros, ou qualquer devolução de mercadoria efetuada pelo MEI com exceção das classificadas nos códigos 1.503, 1.504, 1.505 e 1.506","tipo":"Entrada"},
  {"codigo":"1203","descricao":"Devolução de venda de produção do estabelecimento, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio","tipo":"Entrada"},
  {"codigo":"1204","descricao":"Devolução de venda de mercadoria adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio","tipo":"Entrada"},
  {"codigo":"1205","descricao":"Anulação de valor relativo à prestação de serviço de comunicação","tipo":"Entrada"},
  {"codigo":"1206","descricao":"Anulação de valor relativo à prestação de serviço de transporte","tipo":"Entrada"},
  {"codigo":"1207","descricao":"Anulação de valor relativo à venda de energia elétrica","tipo":"Entrada"},
  {"codigo":"1208","descricao":"Devolução de produção do estabelecimento, remetida em transferência","tipo":"Entrada"},
  {"codigo":"1209","descricao":"Devolução de mercadoria adquirida ou recebida de terceiros, remetida em transferência","tipo":"Entrada"},
  {"codigo":"1212","descricao":"Devolução de venda no mercado interno de mercadoria industrializada e insumo importado sob o Regime Aduaneiro Especial de Entreposto Industrial sob Controle Informatizado do Sistema Público de Escrituração Digital (Recof-Sped)","tipo":"Entrada"},
  {"codigo":"1213","descricao":"Devolução de remessa de produção do estabelecimento, com previsão de posterior ajuste ou fixação de preço, em ato cooperativo","tipo":"Entrada"},
  {"codigo":"1214","descricao":"Devolução referente à fixação de preço de produção do estabelecimento produtor em ato cooperativo","tipo":"Entrada"},
  {"codigo":"1215","descricao":"Devolução de fornecimento de produção do estabelecimento em ato cooperativo","tipo":"Entrada"},
  {"codigo":"1216","descricao":"Devolução de fornecimento de mercadoria adquirida ou recebida de terceiros em ato cooperativo","tipo":"Entrada"},
  {"codigo":"1251","descricao":"Compra de energia elétrica para distribuição ou comercialização","tipo":"Entrada"},
  {"codigo":"1252","descricao":"Compra de energia elétrica por estabelecimento industrial","tipo":"Entrada"},
  {"codigo":"1253","descricao":"Compra de energia elétrica por estabelecimento comercial","tipo":"Entrada"},
  {"codigo":"1254","descricao":"Compra de energia elétrica por estabelecimento prestador de serviço de transporte","tipo":"Entrada"},
  {"codigo":"1255","descricao":"Compra de energia elétrica por estabelecimento prestador de serviço de comunicação","tipo":"Entrada"},
  {"codigo":"1256","descricao":"Compra de energia elétrica por estabelecimento de produtor rural","tipo":"Entrada"},
  {"codigo":"1257","descricao":"Compra de energia elétrica para consumo por demanda contratada","tipo":"Entrada"},
  {"codigo":"1301","descricao":"Aquisição de serviço de comunicação para execução de serviço da mesma natureza","tipo":"Entrada"},
  {"codigo":"1302","descricao":"Aquisição de serviço de comunicação por estabelecimento industrial","tipo":"Entrada"},
  {"codigo":"1303","descricao":"Aquisição de serviço de comunicação por estabelecimento comercial","tipo":"Entrada"},
  {"codigo":"1304","descricao":"Aquisição de serviço de comunicação por estabelecimento de prestador de serviço de transporte","tipo":"Entrada"},
  {"codigo":"1305","descricao":"Aquisição de serviço de comunicação por estabelecimento de geradora ou de distribuidora de energia elétrica","tipo":"Entrada"},
  {"codigo":"1306","descricao":"Aquisição de serviço de comunicação por estabelecimento de produtor rural","tipo":"Entrada"},
  {"codigo":"1351","descricao":"Aquisição de serviço de transporte para execução de serviço da mesma natureza","tipo":"Entrada"},
  {"codigo":"1352","descricao":"Aquisição de serviço de transporte por estabelecimento industrial","tipo":"Entrada"},
  {"codigo":"1353","descricao":"Aquisição de serviço de transporte por estabelecimento comercial","tipo":"Entrada"},
  {"codigo":"1354","descricao":"Aquisição de serviço de transporte por estabelecimento de prestador de serviço de comunicação","tipo":"Entrada"},
  {"codigo":"1355","descricao":"Aquisição de serviço de transporte por estabelecimento de geradora ou de distribuidora de energia elétrica","tipo":"Entrada"},
  {"codigo":"1356","descricao":"Aquisição de serviço de transporte por estabelecimento de produtor rural","tipo":"Entrada"},
  {"codigo":"1360","descricao":"Aquisição de serviço de transporte por contribuinte substituto em relação ao serviço de transporte","tipo":"Entrada"},
  {"codigo":"1401","descricao":"Compra para industrialização ou produção rural em operação com mercadoria sujeita ao regime de substituição tributária","tipo":"Entrada"},
  {"codigo":"1403","descricao":"Compra para comercialização em operação com mercadoria sujeita ao regime de substituição tributária","tipo":"Entrada"},
  {"codigo":"1406","descricao":"Compra de bem para o ativo imobilizado cuja mercadoria está sujeita ao regime de substituição tributária","tipo":"Entrada"},
  {"codigo":"1407","descricao":"Compra de mercadoria para uso ou consumo cuja mercadoria está sujeita ao regime de substituição tributária","tipo":"Entrada"},
  {"codigo":"1408","descricao":"Transferência para industrialização ou produção rural em operação com mercadoria sujeita ao regime de substituição tributária","tipo":"Entrada"},
  {"codigo":"1409","descricao":"Transferência para comercialização em operação com mercadoria sujeita ao regime de substituição tributária","tipo":"Entrada"},
  {"codigo":"1410","descricao":"Devolução de venda de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária","tipo":"Entrada"},
  {"codigo":"1411","descricao":"Devolução de venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária","tipo":"Entrada"},
  {"codigo":"1414","descricao":"Retorno de produção do estabelecimento, remetida para venda fora do estabelecimento em operação com produto sujeito ao regime de substituição tributária","tipo":"Entrada"},
  {"codigo":"1415","descricao":"Retorno de mercadoria adquirida ou recebida de terceiros, remetida para venda fora do estabelecimento em operação com mercadoria sujeita ao regime de substituição tributária","tipo":"Entrada"},
  {"codigo":"1451","descricao":"Entrada de animal - Sistema de Integração e Parceria Rural","tipo":"Entrada"},
  {"codigo":"1452","descricao":"Entrada de insumo - Sistema de Integração e Parceria Rural","tipo":"Entrada"},
  {"codigo":"1453","descricao":"Retorno do animal ou da produção - Sistema de Integração e Parceria Rural","tipo":"Entrada"},
  {"codigo":"1454","descricao":"Retorno simbólico do animal ou da produção - Sistema de Integração e Parceria Rural","tipo":"Entrada"},
  {"codigo":"1455","descricao":"Retorno de insumo não utilizado na produção - Sistema de Integração e Parceria Rural","tipo":"Entrada"},
  {"codigo":"1456","descricao":"Entrada referente à remuneração do produtor no Sistema de Integração e Parceria Rural","tipo":"Entrada"},
  {"codigo":"1501","descricao":"Entrada de mercadoria recebida com fim específico de exportação","tipo":"Entrada"},
  {"codigo":"1503","descricao":"Entrada decorrente de devolução de produto remetido com fim específico de exportação, de produção do estabelecimento","tipo":"Entrada"},
  {"codigo":"1504","descricao":"Entrada decorrente de devolução, inclusive simbólica, de mercadoria remetida com fim específico de exportação, adquirida ou recebida de terceiros","tipo":"Entrada"},
  {"codigo":"1505","descricao":"Entrada decorrente de devolução, inclusive simbólica, de mercadorias remetidas para formação de lote de exportação, de produtos industrializados ou produzidos pelo próprio estabelecimento","tipo":"Entrada"},
  {"codigo":"1506","descricao":"Entrada decorrente de devolução, inclusive simbólica, de mercadorias adquiridas ou recebidas de terceiros, remetidas para formação de lote de exportação","tipo":"Entrada"},
  {"codigo":"1551","descricao":"Compra de bem para o ativo imobilizado","tipo":"Entrada"},
  {"codigo":"1552","descricao":"Transferência de bem do ativo imobilizado","tipo":"Entrada"},
  {"codigo":"1553","descricao":"Devolução de venda de bem do ativo imobilizado","tipo":"Entrada"},
  {"codigo":"1554","descricao":"Retorno de bem do ativo imobilizado remetido para uso fora do estabelecimento","tipo":"Entrada"},
  {"codigo":"1555","descricao":"Entrada de bem do ativo imobilizado de terceiro, remetido para uso no estabelecimento","tipo":"Entrada"},
  {"codigo":"1556","descricao":"Compra de material para uso ou consumo","tipo":"Entrada"},
  {"codigo":"1557","descricao":"Transferência de material para uso ou consumo","tipo":"Entrada"},
  {"codigo":"1601","descricao":"Recebimento, por transferência, de crédito de ICMS","tipo":"Entrada"},
  {"codigo":"1602","descricao":"Recebimento, por transferência, de saldo credor de ICMS de outro estabelecimento da mesma empresa, para compensação de saldo devedor de ICMS","tipo":"Entrada"},
  {"codigo":"1603","descricao":"Ressarcimento de ICMS retido por substituição tributária","tipo":"Entrada"},
  {"codigo":"1604","descricao":"Lançamento do crédito relativo à compra de bem para o ativo imobilizado","tipo":"Entrada"},
  {"codigo":"1605","descricao":"Recebimento, por transferência, de saldo devedor de ICMS de outro estabelecimento da mesma empresa","tipo":"Entrada"},
  {"codigo":"1651","descricao":"Compra de combustíveis ou lubrificantes para industrialização subsequente","tipo":"Entrada"},
  {"codigo":"1652","descricao":"Compra de combustíveis ou lubrificantes para comercialização","tipo":"Entrada"},
  {"codigo":"1653","descricao":"Compra de combustíveis ou lubrificantes por consumidor ou usuário final","tipo":"Entrada"},
  {"codigo":"1657","descricao":"Retorno de remessa de combustíveis ou lubrificantes para venda fora do estabelecimento","tipo":"Entrada"},
  {"codigo":"1658","descricao":"Transferência de combustíveis ou lubrificantes para industrialização","tipo":"Entrada"},
  {"codigo":"1659","descricao":"Transferência de combustíveis ou lubrificantes para comercialização","tipo":"Entrada"},
  {"codigo":"1660","descricao":"Devolução de venda de combustíveis ou lubrificantes destinados à industrialização subsequente","tipo":"Entrada"},
  {"codigo":"1661","descricao":"Devolução de venda de combustíveis ou lubrificantes destinados à comercialização","tipo":"Entrada"},
  {"codigo":"1662","descricao":"Devolução de venda de combustíveis ou lubrificantes destinados a consumidor ou usuário final","tipo":"Entrada"},
  {"codigo":"1663","descricao":"Entrada de combustíveis ou lubrificantes para armazenagem","tipo":"Entrada"},
  {"codigo":"1664","descricao":"Retorno de combustíveis ou lubrificantes remetidos para armazenagem","tipo":"Entrada"},
  {"codigo":"1901","descricao":"Entrada para industrialização por encomenda","tipo":"Entrada"},
  {"codigo":"1902","descricao":"Retorno de mercadoria remetida para industrialização por encomenda","tipo":"Entrada"},
  {"codigo":"1903","descricao":"Entrada de mercadoria remetida para industrialização e não aplicada no referido processo","tipo":"Entrada"},
  {"codigo":"1904","descricao":"Retorno de remessa para venda fora do estabelecimento, ou qualquer entrada e retorno de remessa efetuada pelo MEI com exceção dos classificados nos códigos 1.202, 1.503, 1.504, 1.505 e 1.506","tipo":"Entrada"},
  {"codigo":"1905","descricao":"Entrada de mercadoria recebida para depósito em depósito fechado, armazém geral ou outro estabelecimento da mesma empresa ou de terceiro","tipo":"Entrada"},
  {"codigo":"1906","descricao":"Retorno de mercadoria remetida para depósito fechado, armazém geral ou outro estabelecimento, da mesma empresa ou de terceiro","tipo":"Entrada"},
  {"codigo":"1907","descricao":"Retorno simbólico de mercadoria remetida para depósito fechado, armazém geral ou outro estabelecimento da mesma empresa ou de terceiro","tipo":"Entrada"},
  {"codigo":"1908","descricao":"Entrada de bem por conta de contrato de comodato ou locação","tipo":"Entrada"},
  {"codigo":"1909","descricao":"Retorno de bem remetido por conta de contrato de comodato ou locação","tipo":"Entrada"},
  {"codigo":"1910","descricao":"Entrada de bonificação, doação ou brinde","tipo":"Entrada"},
  {"codigo":"1911","descricao":"Entrada de amostra grátis","tipo":"Entrada"},
  {"codigo":"1912","descricao":"Entrada de mercadoria ou bem recebido para demonstração ou mostruário","tipo":"Entrada"},
  {"codigo":"1913","descricao":"Retorno de mercadoria ou bem remetido para demonstração, mostruário ou treinamento","tipo":"Entrada"},
  {"codigo":"1914","descricao":"Retorno de mercadoria ou bem remetido para exposição ou feira","tipo":"Entrada"},
  {"codigo":"1915","descricao":"Entrada de mercadoria ou bem recebido para conserto ou reparo","tipo":"Entrada"},
  {"codigo":"1916","descricao":"Retorno de mercadoria ou bem remetido para conserto ou reparo","tipo":"Entrada"},
  {"codigo":"1917","descricao":"Entrada de mercadoria recebida em consignação mercantil ou industrial","tipo":"Entrada"},
  {"codigo":"1918","descricao":"Devolução de mercadoria remetida em consignação mercantil ou industrial","tipo":"Entrada"},
  {"codigo":"1919","descricao":"Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, remetida anteriormente em consignação mercantil ou industrial","tipo":"Entrada"},
  {"codigo":"1920","descricao":"Entrada de embalagens, bombonas, vasilhames, sacarias, pallets ou assemelhados","tipo":"Entrada"},
  {"codigo":"1921","descricao":"Retorno de embalagens, bombonas, vasilhames, sacarias, pallets ou assemelhados","tipo":"Entrada"},
  {"codigo":"1922","descricao":"Lançamento efetuado a título de simples faturamento decorrente de compra para recebimento futuro","tipo":"Entrada"},
  {"codigo":"1923","descricao":"Entrada de mercadoria recebida do vendedor remetente, em venda à ordem","tipo":"Entrada"},
  {"codigo":"1924","descricao":"Entrada para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente","tipo":"Entrada"},
  {"codigo":"1925","descricao":"Retorno de mercadoria remetida para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente","tipo":"Entrada"},
  {"codigo":"1926","descricao":"Lançamento efetuado a título de reclassificação de mercadoria decorrente de formação de kit ou de sua desagregação","tipo":"Entrada"},
  {"codigo":"1931","descricao":"Lançamento efetuado pelo tomador do serviço de transporte quando a responsabilidade de retenção do imposto for atribuída ao remetente ou alienante da mercadoria, pelo serviço de transporte realizado por transportador autônomo ou por transportador não inscrito na unidade da Federação onde iniciado o serviço","tipo":"Entrada"},
  {"codigo":"1932","descricao":"Aquisição de serviço de transporte iniciado em unidade da Federação diversa daquela onde inscrito o prestador","tipo":"Entrada"},
  {"codigo":"1933","descricao":"Aquisição de serviço sujeito ao ISSQN","tipo":"Entrada"},
  {"codigo":"1934","descricao":"Entrada simbólica de mercadoria recebida para depósito em depósito fechado ou armazém geral","tipo":"Entrada"},
  {"codigo":"1949","descricao":"Outra entrada de mercadoria ou prestação de serviço não especificada","tipo":"Entrada"},
  {"codigo":"2101","descricao":"Compra para industrialização ou produção rural","tipo":"Entrada"},
  {"codigo":"2102","descricao":"Compra para comercialização","tipo":"Entrada"},
  {"codigo":"2111","descricao":"Compra para industrialização de mercadoria recebida anteriormente em consignação industrial","tipo":"Entrada"},
  {"codigo":"2113","descricao":"Compra para comercialização, de mercadoria recebida anteriormente em consignação mercantil","tipo":"Entrada"},
  {"codigo":"2116","descricao":"Compra para industrialização ou produção rural originada de encomenda para recebimento futuro","tipo":"Entrada"},
  {"codigo":"2117","descricao":"Compra para comercialização originada de encomenda para recebimento futuro","tipo":"Entrada"},
  {"codigo":"2118","descricao":"Compra de mercadoria para comercialização pelo adquirente originário, entregue pelo vendedor remetente ao destinatário, em venda à ordem","tipo":"Entrada"},
  {"codigo":"2120","descricao":"Compra para industrialização ou produção rural, em venda à ordem, já recebida do vendedor remetente","tipo":"Entrada"},
  {"codigo":"2121","descricao":"Compra para comercialização, em venda à ordem, já recebida do vendedor remetente","tipo":"Entrada"},
  {"codigo":"2122","descricao":"Compra para industrialização em que a mercadoria foi remetida pelo fornecedor ao industrializador sem transitar pelo estabelecimento adquirente","tipo":"Entrada"},
  {"codigo":"2124","descricao":"Industrialização efetuada por outra empresa","tipo":"Entrada"},
  {"codigo":"2125","descricao":"Industrialização efetuada por outra empresa quando a mercadoria remetida para utilização no processo de industrialização não transitou pelo estabelecimento adquirente da mercadoria","tipo":"Entrada"},
  {"codigo":"2126","descricao":"Compra para utilização na prestação de serviço sujeita ao ICMS","tipo":"Entrada"},
  {"codigo":"2128","descricao":"Compra para utilização na prestação de serviço sujeita ao ISSQN","tipo":"Entrada"},
  {"codigo":"2131","descricao":"Entrada de mercadoria, com previsão de posterior ajuste ou fixação de preço, em ato cooperativo","tipo":"Entrada"},
  {"codigo":"2132","descricao":"Fixação de preço de produção do estabelecimento produtor, inclusive quando remetidas anteriormente com previsão de posterior ajuste ou fixação de preço, em ato cooperativo, para comercialização","tipo":"Entrada"},
  {"codigo":"2135","descricao":"Fixação de preço de produção do estabelecimento produtor, inclusive quando remetidas anteriormente com previsão de posterior ajuste ou fixação de preço, em ato cooperativo, para industrialização","tipo":"Entrada"},
  {"codigo":"2151","descricao":"Transferência para industrialização ou produção rural","tipo":"Entrada"},
  {"codigo":"2152","descricao":"Transferência para comercialização","tipo":"Entrada"},
  {"codigo":"2153","descricao":"Transferência de energia elétrica para distribuição","tipo":"Entrada"},
  {"codigo":"2154","descricao":"Transferência para utilização na prestação de serviço","tipo":"Entrada"},
  {"codigo":"2159","descricao":"Entrada decorrente do fornecimento de produto ou mercadoria em ato cooperativo","tipo":"Entrada"},
  {"codigo":"2201","descricao":"Devolução de venda de produção do estabelecimento","tipo":"Entrada"},
  {"codigo":"2202","descricao":"Devolução de venda de mercadoria adquirida ou recebida de terceiros, ou qualquer devolução de mercadoria efetuada pelo MEI com exceção das classificadas nos códigos 2.503, 2.504, 2.505 e 2.506","tipo":"Entrada"},
  {"codigo":"2203","descricao":"Devolução de venda de produção do estabelecimento, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio","tipo":"Entrada"},
  {"codigo":"2204","descricao":"Devolução de venda de mercadoria adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio","tipo":"Entrada"},
  {"codigo":"2205","descricao":"Anulação de valor relativo à prestação de serviço de comunicação","tipo":"Entrada"},
  {"codigo":"2206","descricao":"Anulação de valor relativo à prestação de serviço de transporte","tipo":"Entrada"},
  {"codigo":"2207","descricao":"Anulação de valor relativo à venda de energia elétrica","tipo":"Entrada"},
  {"codigo":"2208","descricao":"Devolução de produção do estabelecimento, remetida em transferência","tipo":"Entrada"},
  {"codigo":"2209","descricao":"Devolução de mercadoria adquirida ou recebida de terceiros, remetida em transferência","tipo":"Entrada"},
  {"codigo":"2212","descricao":"Devolução de venda no mercado interno de mercadoria industrializada e insumo importado sob o Regime Aduaneiro Especial de Entreposto Industrial sob Controle Informatizado do Sistema Público de Escrituração Digital (Recof-Sped)","tipo":"Entrada"},
  {"codigo":"2213","descricao":"Devolução de remessa de produção do estabelecimento, com previsão de posterior ajuste ou fixação de preço, em ato cooperativo","tipo":"Entrada"},
  {"codigo":"2214","descricao":"Devolução referente à fixação de preço de produção do estabelecimento produtor, em ato cooperativo","tipo":"Entrada"},
  {"codigo":"2215","descricao":"Devolução de fornecimento de produção do estabelecimento em ato cooperativo","tipo":"Entrada"},
  {"codigo":"2216","descricao":"Devolução de fornecimento de mercadoria adquirida ou recebida de terceiros em ato cooperativo","tipo":"Entrada"},
  {"codigo":"2251","descricao":"Compra de energia elétrica para distribuição ou comercialização","tipo":"Entrada"},
  {"codigo":"2252","descricao":"Compra de energia elétrica por estabelecimento industrial","tipo":"Entrada"},
  {"codigo":"2253","descricao":"Compra de energia elétrica por estabelecimento comercial","tipo":"Entrada"},
  {"codigo":"2254","descricao":"Compra de energia elétrica por estabelecimento prestador de serviço de transporte","tipo":"Entrada"},
  {"codigo":"2255","descricao":"Compra de energia elétrica por estabelecimento prestador de serviço de comunicação","tipo":"Entrada"},
  {"codigo":"2256","descricao":"Compra de energia elétrica por estabelecimento de produtor rural","tipo":"Entrada"},
  {"codigo":"2257","descricao":"Compra de energia elétrica para consumo por demanda contratada","tipo":"Entrada"},
  {"codigo":"2301","descricao":"Aquisição de serviço de comunicação para execução de serviço da mesma natureza","tipo":"Entrada"},
  {"codigo":"2302","descricao":"Aquisição de serviço de comunicação por estabelecimento industrial","tipo":"Entrada"},
  {"codigo":"2303","descricao":"Aquisição de serviço de comunicação por estabelecimento comercial","tipo":"Entrada"},
  {"codigo":"2304","descricao":"Aquisição de serviço de comunicação por estabelecimento de prestador de serviço de transporte","tipo":"Entrada"},
  {"codigo":"2305","descricao":"Aquisição de serviço de comunicação por estabelecimento de geradora ou de distribuidora de energia elétrica","tipo":"Entrada"},
  {"codigo":"2306","descricao":"Aquisição de serviço de comunicação por estabelecimento de produtor rural","tipo":"Entrada"},
  {"codigo":"2351","descricao":"Aquisição de serviço de transporte para execução de serviço da mesma natureza","tipo":"Entrada"},
  {"codigo":"2352","descricao":"Aquisição de serviço de transporte por estabelecimento industrial","tipo":"Entrada"},
  {"codigo":"2353","descricao":"Aquisição de serviço de transporte por estabelecimento comercial","tipo":"Entrada"},
  {"codigo":"2354","descricao":"Aquisição de serviço de transporte por estabelecimento de prestador de serviço de comunicação","tipo":"Entrada"},
  {"codigo":"2355","descricao":"Aquisição de serviço de transporte por estabelecimento de geradora ou de distribuidora de energia elétrica","tipo":"Entrada"},
  {"codigo":"2356","descricao":"Aquisição de serviço de transporte por estabelecimento de produtor rural","tipo":"Entrada"},
  {"codigo":"2401","descricao":"Compra para industrialização ou produção rural em operação com mercadoria sujeita ao regime de substituição tributária","tipo":"Entrada"},
  {"codigo":"2403","descricao":"Compra para comercialização em operação com mercadoria sujeita ao regime de substituição tributária","tipo":"Entrada"},
  {"codigo":"2406","descricao":"Compra de bem para o ativo imobilizado cuja mercadoria está sujeita ao regime de substituição tributária","tipo":"Entrada"},
  {"codigo":"2407","descricao":"Compra de mercadoria para uso ou consumo cuja mercadoria está sujeita ao regime de substituição tributária","tipo":"Entrada"},
  {"codigo":"2408","descricao":"Transferência para industrialização ou produção rural em operação com mercadoria sujeita ao regime de substituição tributária","tipo":"Entrada"},
  {"codigo":"2409","descricao":"Transferência para comercialização em operação com mercadoria sujeita ao regime de substituição tributária","tipo":"Entrada"},
  {"codigo":"2410","descricao":"Devolução de venda de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária","tipo":"Entrada"},
  {"codigo":"2411","descricao":"Devolução de venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária","tipo":"Entrada"},
  {"codigo":"2414","descricao":"Retorno de produção do estabelecimento, remetida para venda fora do estabelecimento em operação com produto sujeito ao regime de substituição tributária","tipo":"Entrada"},
  {"codigo":"2415","descricao":"Retorno de mercadoria adquirida ou recebida de terceiros, remetida para venda fora do estabelecimento em operação com mercadoria sujeita ao regime de substituição tributária","tipo":"Entrada"},
  {"codigo":"2451","descricao":"Entrada de animal - Sistema de Integração e Parceria Rural","tipo":"Entrada"},
  {"codigo":"2452","descricao":"Entrada de insumo - Sistema de Integração e Parceria Rural","tipo":"Entrada"},
  {"codigo":"2453","descricao":"Retorno do animal ou da produção - Sistema de Integração e Parceria Rural","tipo":"Entrada"},
  {"codigo":"2454","descricao":"Retorno simbólico do animal ou da produção - Sistema de Integração e Parceria Rural","tipo":"Entrada"},
  {"codigo":"2455","descricao":"Retorno de insumo não utilizado na produção - Sistema de Integração e Parceria Rural","tipo":"Entrada"},
  {"codigo":"2456","descricao":"Entrada referente à remuneração do produtor no Sistema de Integração e Parceria Rural","tipo":"Entrada"},
  {"codigo":"2501","descricao":"Entrada de mercadoria recebida com fim específico de exportação","tipo":"Entrada"},
  {"codigo":"2503","descricao":"Entrada decorrente de devolução de produto remetido com fim específico de exportação, de produção do estabelecimento","tipo":"Entrada"},
  {"codigo":"2504","descricao":"Entrada decorrente de devolução, inclusive simbólica, de mercadoria remetida com fim específico de exportação, adquirida ou recebida de terceiros","tipo":"Entrada"},
  {"codigo":"2505","descricao":"Entrada decorrente de devolução, inclusive simbólica, de mercadorias remetidas para formação de lote de exportação, de produtos industrializados ou produzidos pelo próprio estabelecimento","tipo":"Entrada"},
  {"codigo":"2506","descricao":"Entrada decorrente de devolução, inclusive simbólica, de mercadorias adquiridas ou recebidas de terceiros, remetidas para formação de lote de exportação","tipo":"Entrada"},
  {"codigo":"2551","descricao":"Compra de bem para o ativo imobilizado","tipo":"Entrada"},
  {"codigo":"2552","descricao":"Transferência de bem do ativo imobilizado","tipo":"Entrada"},
  {"codigo":"2553","descricao":"Devolução de venda de bem do ativo imobilizado","tipo":"Entrada"},
  {"codigo":"2554","descricao":"Retorno de bem do ativo imobilizado remetido para uso fora do estabelecimento","tipo":"Entrada"},
  {"codigo":"2555","descricao":"Entrada de bem do ativo imobilizado de terceiro, remetido para uso no estabelecimento","tipo":"Entrada"},
  {"codigo":"2556","descricao":"Compra de material para uso ou consumo","tipo":"Entrada"},
  {"codigo":"2557","descricao":"Transferência de material para uso ou consumo","tipo":"Entrada"},
  {"codigo":"2603","descricao":"Ressarcimento de ICMS retido por substituição tributária","tipo":"Entrada"},
  {"codigo":"2651","descricao":"Compra de combustíveis ou lubrificantes para industrialização subsequente","tipo":"Entrada"},
  {"codigo":"2652","descricao":"Compra de combustíveis ou lubrificantes para comercialização","tipo":"Entrada"},
  {"codigo":"2653","descricao":"Compra de combustíveis ou lubrificantes por consumidor ou usuário final","tipo":"Entrada"},
  {"codigo":"2657","descricao":"Retorno de remessa de combustíveis ou lubrificantes para venda fora do estabelecimento","tipo":"Entrada"},
  {"codigo":"2658","descricao":"Transferência de combustíveis ou lubrificantes para industrialização","tipo":"Entrada"},
  {"codigo":"2659","descricao":"Transferência de combustíveis ou lubrificantes para comercialização","tipo":"Entrada"},
  {"codigo":"2660","descricao":"Devolução de venda de combustíveis ou lubrificantes destinados à industrialização subsequente","tipo":"Entrada"},
  {"codigo":"2661","descricao":"Devolução de venda de combustíveis ou lubrificantes destinados à comercialização","tipo":"Entrada"},
  {"codigo":"2662","descricao":"Devolução de venda de combustíveis ou lubrificantes destinados a consumidor ou usuário final","tipo":"Entrada"},
  {"codigo":"2663","descricao":"Entrada de combustíveis ou lubrificantes para armazenagem","tipo":"Entrada"},
  {"codigo":"2664","descricao":"Retorno de combustíveis ou lubrificantes remetidos para armazenagem","tipo":"Entrada"},
  {"codigo":"2901","descricao":"Entrada para industrialização por encomenda","tipo":"Entrada"},
  {"codigo":"2902","descricao":"Retorno de mercadoria remetida para industrialização por encomenda","tipo":"Entrada"},
  {"codigo":"2903","descricao":"Entrada de mercadoria remetida para industrialização e não aplicada no referido processo","tipo":"Entrada"},
  {"codigo":"2904","descricao":"Retorno de remessa para venda fora do estabelecimento, ou qualquer entrada e retorno de remessa efetuada pelo MEI com exceção dos classificados nos códigos 2.202, 2.503, 2.504, 2.505 e 2.506","tipo":"Entrada"},
  {"codigo":"2905","descricao":"Entrada de mercadoria recebida para depósito em depósito fechado, armazém geral ou outro estabelecimento da mesma empresa ou de terceiro","tipo":"Entrada"},
  {"codigo":"2906","descricao":"Retorno de mercadoria remetida para depósito fechado, armazém geral ou outro estabelecimento da mesma empresa ou de terceiro","tipo":"Entrada"},
  {"codigo":"2907","descricao":"Retorno simbólico de mercadoria remetida para depósito fechado, armazém geral ou outro estabelecimento da mesma empresa ou de terceiro","tipo":"Entrada"},
  {"codigo":"2908","descricao":"Entrada de bem por conta de contrato de comodato ou locação","tipo":"Entrada"},
  {"codigo":"2909","descricao":"Retorno de bem remetido por conta de contrato de comodato ou locação","tipo":"Entrada"},
  {"codigo":"2910","descricao":"Entrada de bonificação, doação ou brinde","tipo":"Entrada"},
  {"codigo":"2911","descricao":"Entrada de amostra grátis","tipo":"Entrada"},
  {"codigo":"2912","descricao":"Entrada de mercadoria ou bem recebido para demonstração ou mostruário","tipo":"Entrada"},
  {"codigo":"2913","descricao":"Retorno de mercadoria ou bem remetido para demonstração, mostruário ou treinamento","tipo":"Entrada"},
  {"codigo":"2914","descricao":"Retorno de mercadoria ou bem remetido para exposição ou feira","tipo":"Entrada"},
  {"codigo":"2915","descricao":"Entrada de mercadoria ou bem recebido para conserto ou reparo","tipo":"Entrada"},
  {"codigo":"2916","descricao":"Retorno de mercadoria ou bem remetido para conserto ou reparo","tipo":"Entrada"},
  {"codigo":"2917","descricao":"Entrada de mercadoria recebida em consignação mercantil ou industrial","tipo":"Entrada"},
  {"codigo":"2918","descricao":"Devolução de mercadoria remetida em consignação mercantil ou industrial","tipo":"Entrada"},
  {"codigo":"2919","descricao":"Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, remetida anteriormente em consignação mercantil ou industrial","tipo":"Entrada"},
  {"codigo":"2920","descricao":"Entrada de embalagens, bombonas, vasilhames, sacarias, pallets ou assemelhados","tipo":"Entrada"},
  {"codigo":"2921","descricao":"Retorno de embalagens, bombonas, vasilhames, sacarias, pallets ou assemelhados","tipo":"Entrada"},
  {"codigo":"2922","descricao":"Lançamento efetuado a título de simples faturamento decorrente de compra para recebimento futuro","tipo":"Entrada"},
  {"codigo":"2923","descricao":"Entrada de mercadoria recebida do vendedor remetente, em venda à ordem","tipo":"Entrada"},
  {"codigo":"2924","descricao":"Entrada para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente","tipo":"Entrada"},
  {"codigo":"2925","descricao":"Retorno de mercadoria remetida para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente","tipo":"Entrada"},
  {"codigo":"2931","descricao":"Lançamento efetuado pelo tomador do serviço de transporte quando a responsabilidade de retenção do imposto for atribuída ao remetente ou alienante da mercadoria, pelo serviço de transporte realizado por transportador autônomo ou por transportador não inscrito na unidade da Federação onde iniciado o serviço","tipo":"Entrada"},
  {"codigo":"2932","descricao":"Aquisição de serviço de transporte iniciado em unidade da Federação diversa daquela onde inscrito o prestador","tipo":"Entrada"},
  {"codigo":"2933","descricao":"Aquisição de serviço sujeito ao ISSQN","tipo":"Entrada"},
  {"codigo":"2934","descricao":"Entrada simbólica de mercadoria recebida para depósito em depósito fechado ou armazém geral","tipo":"Entrada"},
  {"codigo":"2949","descricao":"Outra entrada de mercadoria ou prestação de serviço não especificada","tipo":"Entrada"},
  {"codigo":"3101","descricao":"Compra para industrialização ou produção rural","tipo":"Entrada"},
  {"codigo":"3102","descricao":"Compra para comercialização","tipo":"Entrada"},
  {"codigo":"3126","descricao":"Compra para utilização na prestação de serviço sujeita ao ICMS","tipo":"Entrada"},
  {"codigo":"3127","descricao":"Compra para industrialização sob o regime de “drawback”","tipo":"Entrada"},
  {"codigo":"3128","descricao":"Compra para utilização na prestação de serviço sujeita ao ISSQN","tipo":"Entrada"},
  {"codigo":"3129","descricao":"Compra para industrialização sob o Regime Aduaneiro Especial de Entreposto Industrial sob Controle Informatizado do Sistema Público de Escrituração Digital (Recof-Sped)","tipo":"Entrada"},
  {"codigo":"3201","descricao":"Devolução de venda de produção do estabelecimento","tipo":"Entrada"},
  {"codigo":"3202","descricao":"Devolução de venda de mercadoria adquirida ou recebida de terceiros","tipo":"Entrada"},
  {"codigo":"3205","descricao":"Anulação de valor relativo à prestação de serviço de comunicação","tipo":"Entrada"},
  {"codigo":"3206","descricao":"Anulação de valor relativo à prestação de serviço de transporte","tipo":"Entrada"},
  {"codigo":"3207","descricao":"Anulação de valor relativo à venda de energia elétrica","tipo":"Entrada"},
  {"codigo":"3211","descricao":"Devolução de venda de produção do estabelecimento sob o regime de “drawback”","tipo":"Entrada"},
  {"codigo":"3212","descricao":"Devolução de venda no mercado externo de mercadoria industrializada sob o Regime Aduaneiro Especial de Entreposto Industrial sob Controle Informatizado do Sistema Público de Escrituração Digital (Recof-Sped)","tipo":"Entrada"},
  {"codigo":"3251","descricao":"Compra de energia elétrica para distribuição ou comercialização","tipo":"Entrada"},
  {"codigo":"3301","descricao":"Aquisição de serviço de comunicação para execução de serviço da mesma natureza","tipo":"Entrada"},
  {"codigo":"3351","descricao":"Aquisição de serviço de transporte para execução de serviço da mesma natureza","tipo":"Entrada"},
  {"codigo":"3352","descricao":"Aquisição de serviço de transporte por estabelecimento industrial","tipo":"Entrada"},
  {"codigo":"3353","descricao":"Aquisição de serviço de transporte por estabelecimento comercial","tipo":"Entrada"},
  {"codigo":"3354","descricao":"Aquisição de serviço de transporte por estabelecimento de prestador de serviço de comunicação","tipo":"Entrada"},
  {"codigo":"3355","descricao":"Aquisição de serviço de transporte por estabelecimento de geradora ou de distribuidora de energia elétrica","tipo":"Entrada"},
  {"codigo":"3356","descricao":"Aquisição de serviço de transporte por estabelecimento de produtor rural","tipo":"Entrada"},
  {"codigo":"3503","descricao":"Devolução de mercadoria exportada que tenha sido recebida com fim específico de exportação","tipo":"Entrada"},
  {"codigo":"3551","descricao":"Compra de bem para o ativo imobilizado","tipo":"Entrada"},
  {"codigo":"3552","descricao":"Entrada de produto destinado para uso ou consumo de bordo, em embarcações ou aeronaves exclusivamente em tráfego internacional com destino ao exterior","tipo":"Entrada"},
  {"codigo":"3553","descricao":"Devolução de venda de bem do ativo imobilizado","tipo":"Entrada"},
  {"codigo":"3556","descricao":"Compra de material para uso ou consumo","tipo":"Entrada"},
  {"codigo":"3651","descricao":"Compra de combustíveis ou lubrificantes para industrialização subsequente","tipo":"Entrada"},
  {"codigo":"3652","descricao":"Compra de combustíveis ou lubrificantes para comercialização","tipo":"Entrada"},
  {"codigo":"3653","descricao":"Compra de combustíveis ou lubrificantes por consumidor ou usuário final","tipo":"Entrada"},
  {"codigo":"3667","descricao":"Entrada de combustíveis ou lubrificantes para consumo final, em embarcações ou aeronaves exclusivamente em tráfego internacional com destino ao exterior","tipo":"Entrada"},
  {"codigo":"3930","descricao":"Lançamento efetuado a título de entrada de bem sob amparo de regime especial aduaneiro de admissão temporária","tipo":"Entrada"},
  {"codigo":"3949","descricao":"Outra entrada de mercadoria ou prestação de serviço não especificada","tipo":"Entrada"},
  {"codigo":"5101","descricao":"Venda de produção do estabelecimento","tipo":"Saída"},
  {"codigo":"5102","descricao":"Venda de mercadoria adquirida ou recebida de terceiros, ou qualquer venda de mercadoria efetuada pelo MEI com exceção das saídas classificadas nos códigos 5.501, 5.502, 5.504 e 5.505","tipo":"Saída"},
  {"codigo":"5103","descricao":"Venda de produção do estabelecimento, efetuada fora do estabelecimento","tipo":"Saída"},
  {"codigo":"5104","descricao":"Venda de mercadoria adquirida ou recebida de terceiros, efetuada fora do estabelecimento","tipo":"Saída"},
  {"codigo":"5105","descricao":"Venda de produção do estabelecimento que não deva por ele transitar","tipo":"Saída"},
  {"codigo":"5106","descricao":"Venda de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar","tipo":"Saída"},
  {"codigo":"5109","descricao":"Venda de produção do estabelecimento, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio","tipo":"Saída"},
  {"codigo":"5110","descricao":"Venda de mercadoria adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio","tipo":"Saída"},
  {"codigo":"5111","descricao":"Venda de produção do estabelecimento remetida anteriormente em consignação industrial","tipo":"Saída"},
  {"codigo":"5112","descricao":"Venda de mercadoria adquirida ou recebida de terceiros remetida anteriormente em consignação industrial","tipo":"Saída"},
  {"codigo":"5113","descricao":"Venda de produção do estabelecimento remetida anteriormente em consignação mercantil","tipo":"Saída"},
  {"codigo":"5114","descricao":"Venda de mercadoria adquirida ou recebida de terceiros remetida anteriormente em consignação mercantil","tipo":"Saída"},
  {"codigo":"5115","descricao":"Venda de mercadoria adquirida ou recebida de terceiros, recebida anteriormente em consignação mercantil","tipo":"Saída"},
  {"codigo":"5116","descricao":"Venda de produção do estabelecimento originada de encomenda para entrega futura","tipo":"Saída"},
  {"codigo":"5117","descricao":"Venda de mercadoria adquirida ou recebida de terceiros, originada de encomenda para entrega futura","tipo":"Saída"},
  {"codigo":"5118","descricao":"Venda de produção do estabelecimento industrial ou rural, entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem","tipo":"Saída"},
  {"codigo":"5119","descricao":"Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem","tipo":"Saída"},
  {"codigo":"5120","descricao":"Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário pelo vendedor remetente, em venda à ordem","tipo":"Saída"},
  {"codigo":"5122","descricao":"Venda de produção do estabelecimento remetida para industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente","tipo":"Saída"},
  {"codigo":"5123","descricao":"Venda de mercadoria adquirida ou recebida de terceiros remetida para industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente","tipo":"Saída"},
  {"codigo":"5124","descricao":"Industrialização efetuada para outra empresa","tipo":"Saída"},
  {"codigo":"5125","descricao":"Industrialização efetuada para outra empresa quando a mercadoria recebida para utilização no processo de industrialização não transitar pelo estabelecimento adquirente da mercadoria","tipo":"Saída"},
  {"codigo":"5129","descricao":"Venda de mercadoria industrializada e de insumo importado sob o amparo do Regime Aduaneiro Especial de Entreposto Industrial sob Controle Informatizado do Sistema Público de Escrituração Digital (Recof-Sped)","tipo":"Saída"},
  {"codigo":"5131","descricao":"Remessa de produção do estabelecimento, com previsão de posterior ajuste ou fixação de preço, em ato cooperativo","tipo":"Saída"},
  {"codigo":"5132","descricao":"Fixação de preço de produção do estabelecimento, inclusive quando remetidas anteriormente com previsão de posterior ajuste ou fixação de preço, em ato cooperativo","tipo":"Saída"},
  {"codigo":"5151","descricao":"Transferência de produção do estabelecimento","tipo":"Saída"},
  {"codigo":"5152","descricao":"Transferência de mercadoria adquirida ou recebida de terceiros","tipo":"Saída"},
  {"codigo":"5153","descricao":"Transferência de energia elétrica","tipo":"Saída"},
  {"codigo":"5155","descricao":"Transferência de produção do estabelecimento para depósito em depósito fechado, armazém geral ou outro estabelecimento da mesma empresa ou de terceiro, que não deva por ele transitar","tipo":"Saída"},
  {"codigo":"5156","descricao":"Transferência de mercadoria adquirida ou recebida de terceiros para depósito em depósito fechado, armazém geral ou outro estabelecimento da mesma empresa ou de terceiro, que não deva por ele transitar","tipo":"Saída"},
  {"codigo":"5159","descricao":"Fornecimento de produção do estabelecimento em ato cooperativo","tipo":"Saída"},
  {"codigo":"5160","descricao":"Fornecimento de mercadoria adquirida ou recebida de terceiros em ato cooperativo","tipo":"Saída"},
  {"codigo":"5201","descricao":"Devolução de compra para industrialização ou produção rural","tipo":"Saída"},
  {"codigo":"5202","descricao":"Devolução de compra para comercialização, ou qualquer devolução de mercadorias efetuada pelo MEI com exceção das classificadas no código 5.503","tipo":"Saída"},
  {"codigo":"5205","descricao":"Anulação de valor relativo à aquisição de serviço de comunicação","tipo":"Saída"},
  {"codigo":"5206","descricao":"Anulação de valor relativo à aquisição de serviço de transporte","tipo":"Saída"},
  {"codigo":"5207","descricao":"Anulação de valor relativo à compra de energia elétrica","tipo":"Saída"},
  {"codigo":"5208","descricao":"Devolução de mercadoria recebida em transferência para industrialização ou produção rural","tipo":"Saída"},
  {"codigo":"5209","descricao":"Devolução de mercadoria recebida em transferência para comercialização","tipo":"Saída"},
  {"codigo":"5210","descricao":"Devolução de compra para utilização na prestação de serviço","tipo":"Saída"},
  {"codigo":"5213","descricao":"Devolução de entrada, inclusive simbólica, de mercadoria com previsão de posterior ajuste ou fixação de preço, em ato cooperativo","tipo":"Saída"},
  {"codigo":"5214","descricao":"Devolução referente à fixação de preço de produção do estabelecimento produtor, inclusive quando remetidas anteriormente com previsão de posterior ajuste ou fixação de preço, em ato cooperativo, para comercialização","tipo":"Saída"},
  {"codigo":"5215","descricao":"Devolução referente à fixação de preço de produção do estabelecimento produtor, inclusive quando remetidas anteriormente com previsão de posterior ajuste ou fixação de preço, em ato cooperativo, para industrialização","tipo":"Saída"},
  {"codigo":"5216","descricao":"Devolução de entrada decorrente do fornecimento de produto ou mercadoria em ato cooperativo","tipo":"Saída"},
  {"codigo":"5251","descricao":"Venda de energia elétrica para distribuição ou comercialização","tipo":"Saída"},
  {"codigo":"5252","descricao":"Venda de energia elétrica para estabelecimento industrial","tipo":"Saída"},
  {"codigo":"5253","descricao":"Venda de energia elétrica para estabelecimento comercial","tipo":"Saída"},
  {"codigo":"5254","descricao":"Venda de energia elétrica para estabelecimento prestador de serviço de transporte","tipo":"Saída"},
  {"codigo":"5255","descricao":"Venda de energia elétrica para estabelecimento prestador de serviço de comunicação","tipo":"Saída"},
  {"codigo":"5256","descricao":"Venda de energia elétrica para estabelecimento de produtor rural","tipo":"Saída"},
  {"codigo":"5257","descricao":"Venda de energia elétrica para consumo por demanda contratada","tipo":"Saída"},
  {"codigo":"5258","descricao":"Venda de energia elétrica a não contribuinte","tipo":"Saída"},
  {"codigo":"5301","descricao":"Prestação de serviço de comunicação para execução de serviço da mesma natureza","tipo":"Saída"},
  {"codigo":"5302","descricao":"Prestação de serviço de comunicação a estabelecimento industrial","tipo":"Saída"},
  {"codigo":"5303","descricao":"Prestação de serviço de comunicação a estabelecimento comercial","tipo":"Saída"},
  {"codigo":"5304","descricao":"Prestação de serviço de comunicação a estabelecimento de prestador de serviço de transporte","tipo":"Saída"},
  {"codigo":"5305","descricao":"Prestação de serviço de comunicação a estabelecimento de geradora ou de distribuidora de energia elétrica","tipo":"Saída"},
  {"codigo":"5306","descricao":"Prestação de serviço de comunicação a estabelecimento de produtor rural","tipo":"Saída"},
  {"codigo":"5307","descricao":"Prestação de serviço de comunicação a não contribuinte","tipo":"Saída"},
  {"codigo":"5351","descricao":"Prestação de serviço de transporte para execução de serviço da mesma natureza","tipo":"Saída"},
  {"codigo":"5352","descricao":"Prestação de serviço de transporte a estabelecimento industrial","tipo":"Saída"},
  {"codigo":"5353","descricao":"Prestação de serviço de transporte a estabelecimento comercial","tipo":"Saída"},
  {"codigo":"5354","descricao":"Prestação de serviço de transporte a estabelecimento de prestador de serviço de comunicação","tipo":"Saída"},
  {"codigo":"5355","descricao":"Prestação de serviço de transporte a estabelecimento de geradora ou de distribuidora de energia elétrica","tipo":"Saída"},
  {"codigo":"5356","descricao":"Prestação de serviço de transporte a estabelecimento de produtor rural","tipo":"Saída"},
  {"codigo":"5357","descricao":"Prestação de serviço de transporte a não contribuinte","tipo":"Saída"},
  {"codigo":"5359","descricao":"Prestação de serviço de transporte a contribuinte ou a não contribuinte quando a mercadoria transportada está dispensada de emissão de nota fiscal","tipo":"Saída"},
  {"codigo":"5360","descricao":"Prestação de serviço de transporte a contribuinte substituto em relação ao serviço de transporte","tipo":"Saída"},
  {"codigo":"5401","descricao":"Venda de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária, na condição de contribuinte substituto","tipo":"Saída"},
  {"codigo":"5402","descricao":"Venda de produção do estabelecimento de produto sujeito ao regime de substituição tributária, em operação entre contribuintes substitutos do mesmo produto","tipo":"Saída"},
  {"codigo":"5403","descricao":"Venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária, na condição de contribuinte substituto","tipo":"Saída"},
  {"codigo":"5405","descricao":"Venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária, na condição de contribuinte substituído","tipo":"Saída"},
  {"codigo":"5408","descricao":"Transferência de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária","tipo":"Saída"},
  {"codigo":"5409","descricao":"Transferência de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária","tipo":"Saída"},
  {"codigo":"5410","descricao":"Devolução de compra para industrialização ou produção rural em operação com mercadoria sujeita ao regime de substituição tributária","tipo":"Saída"},
  {"codigo":"5411","descricao":"Devolução de compra para comercialização em operação com mercadoria sujeita ao regime de substituição tributária","tipo":"Saída"},
  {"codigo":"5412","descricao":"Devolução de bem do ativo imobilizado, em operação com mercadoria sujeita ao regime de substituição tributária","tipo":"Saída"},
  {"codigo":"5413","descricao":"Devolução de mercadoria destinada para uso ou consumo, em operação com mercadoria sujeita ao regime de substituição tributária","tipo":"Saída"},
  {"codigo":"5414","descricao":"Remessa de produção do estabelecimento para venda fora do estabelecimento em operação com produto sujeito ao regime de substituição tributária","tipo":"Saída"},
  {"codigo":"5415","descricao":"Remessa de mercadoria adquirida ou recebida de terceiros para venda fora do estabelecimento, em operação com mercadoria sujeita ao regime de substituição tributária","tipo":"Saída"},
  {"codigo":"5451","descricao":"Remessa de animal - Sistema de Integração e Parceria Rural","tipo":"Saída"},
  {"codigo":"5452","descricao":"Remessa de insumo - Sistema de Integração e Parceria Rural","tipo":"Saída"},
  {"codigo":"5453","descricao":"Retorno de animal ou da produção - Sistema de Integração e Parceria Rural","tipo":"Saída"},
  {"codigo":"5454","descricao":"Retorno simbólico de animal ou da produção - Sistema de Integração e Parceria Rural","tipo":"Saída"},
  {"codigo":"5455","descricao":"Retorno de insumos não utilizados na produção - Sistema de Integração e Parceria Rural","tipo":"Saída"},
  {"codigo":"5456","descricao":"Saída referente à remuneração do produtor - Sistema de Integração e Parceria Rural","tipo":"Saída"},
  {"codigo":"5501","descricao":"Remessa de produção do estabelecimento, com fim específico de exportação","tipo":"Saída"},
  {"codigo":"5502","descricao":"Remessa de mercadoria adquirida ou recebida de terceiros, com fim específico de exportação","tipo":"Saída"},
  {"codigo":"5503","descricao":"Devolução de mercadoria recebida com fim específico de exportação","tipo":"Saída"},
  {"codigo":"5504","descricao":"Remessa de mercadorias para formação de lote de exportação, de produtos industrializados ou produzidos pelo próprio estabelecimento","tipo":"Saída"},
  {"codigo":"5505","descricao":"Remessa de mercadorias, adquiridas ou recebidas de terceiros, para formação de lote de exportação","tipo":"Saída"},
  {"codigo":"5551","descricao":"Venda de bem do ativo imobilizado","tipo":"Saída"},
  {"codigo":"5552","descricao":"Transferência de bem do ativo imobilizado","tipo":"Saída"},
  {"codigo":"5553","descricao":"Devolução de compra de bem para o ativo imobilizado","tipo":"Saída"},
  {"codigo":"5554","descricao":"Remessa de bem do ativo imobilizado para uso fora do estabelecimento","tipo":"Saída"},
  {"codigo":"5555","descricao":"Devolução de bem do ativo imobilizado de terceiro, recebido para uso no estabelecimento","tipo":"Saída"},
  {"codigo":"5556","descricao":"Devolução de compra de material para uso ou consumo","tipo":"Saída"},
  {"codigo":"5557","descricao":"Transferência de material para uso ou consumo","tipo":"Saída"},
  {"codigo":"5601","descricao":"Transferência de crédito de ICMS acumulado","tipo":"Saída"},
  {"codigo":"5602","descricao":"Transferência de saldo credor de ICMS para outro estabelecimento da mesma empresa, destinado à compensação de saldo devedor de ICMS","tipo":"Saída"},
  {"codigo":"5603","descricao":"Ressarcimento de ICMS retido por substituição tributária","tipo":"Saída"},
  {"codigo":"5605","descricao":"Transferência de saldo devedor de ICMS para outro estabelecimento da mesma empresa","tipo":"Saída"},
  {"codigo":"5606","descricao":"Utilização de saldo credor de ICMS para extinção por compensação de débitos fiscais","tipo":"Saída"},
  {"codigo":"5651","descricao":"Venda de combustíveis ou lubrificantes de produção do estabelecimento destinados à industrialização subsequente","tipo":"Saída"},
  {"codigo":"5652","descricao":"Venda de combustíveis ou lubrificantes de produção do estabelecimento destinados à comercialização","tipo":"Saída"},
  {"codigo":"5653","descricao":"Venda de combustíveis ou lubrificantes de produção do estabelecimento destinados a consumidor ou usuário final","tipo":"Saída"},
  {"codigo":"5654","descricao":"Venda de combustíveis ou lubrificantes adquiridos ou recebidos de terceiros destinados à industrialização subsequente","tipo":"Saída"},
  {"codigo":"5655","descricao":"Venda de combustíveis ou lubrificantes adquiridos ou recebidos de terceiros destinados à comercialização","tipo":"Saída"},
  {"codigo":"5656","descricao":"Venda de combustíveis ou lubrificantes adquiridos ou recebidos de terceiros destinados a consumidor ou usuário final","tipo":"Saída"},
  {"codigo":"5657","descricao":"Remessa de combustíveis ou lubrificantes adquiridos ou recebidos de terceiros para venda fora do estabelecimento","tipo":"Saída"},
  {"codigo":"5658","descricao":"Transferência de combustíveis ou lubrificantes de produção do estabelecimento","tipo":"Saída"},
  {"codigo":"5659","descricao":"Transferência de combustíveis ou lubrificantes adquiridos ou recebidos de terceiros","tipo":"Saída"},
  {"codigo":"5660","descricao":"Devolução de compra de combustíveis ou lubrificantes adquiridos para industrialização subsequente","tipo":"Saída"},
  {"codigo":"5661","descricao":"Devolução de compra de combustíveis ou lubrificantes adquiridos para comercialização","tipo":"Saída"},
  {"codigo":"5662","descricao":"Devolução de compra de combustíveis ou lubrificantes adquiridos por consumidor ou usuário final","tipo":"Saída"},
  {"codigo":"5663","descricao":"Remessa para armazenagem de combustíveis ou lubrificantes","tipo":"Saída"},
  {"codigo":"5664","descricao":"Retorno de combustíveis ou lubrificantes recebidos para armazenagem","tipo":"Saída"},
  {"codigo":"5665","descricao":"Retorno simbólico de combustíveis ou lubrificantes recebidos para armazenagem","tipo":"Saída"},
  {"codigo":"5666","descricao":"Remessa por conta e ordem de terceiros de combustíveis ou lubrificantes recebidos para armazenagem","tipo":"Saída"},
  {"codigo":"5667","descricao":"Venda de combustíveis ou lubrificantes a consumidor ou usuário final estabelecido em outra unidade da Federação","tipo":"Saída"},
  {"codigo":"5901","descricao":"Remessa para industrialização por encomenda","tipo":"Saída"},
  {"codigo":"5902","descricao":"Retorno de mercadoria utilizada na industrialização por encomenda","tipo":"Saída"},
  {"codigo":"5903","descricao":"Retorno de mercadoria recebida para industrialização e não aplicada no referido processo","tipo":"Saída"},
  {"codigo":"5904","descricao":"Remessa para venda fora do estabelecimento, ou qualquer remessa efetuada pelo MEI com exceção das classificadas nos códigos 5.502 e 5.505","tipo":"Saída"},
  {"codigo":"5905","descricao":"Remessa para depósito fechado, armazém geral ou outro estabelecimento da mesma empresa ou de terceiro","tipo":"Saída"},
  {"codigo":"5906","descricao":"Retorno de mercadoria depositada em depósito fechado, armazém geral ou outro estabelecimento da mesma empresa ou de terceiro","tipo":"Saída"},
  {"codigo":"5907","descricao":"Retorno simbólico de mercadoria depositada em depósito fechado, armazém geral ou outro estabelecimento da mesma empresa ou de terceiro","tipo":"Saída"},
  {"codigo":"5908","descricao":"Remessa de bem por conta de contrato de comodato ou locação","tipo":"Saída"},
  {"codigo":"5909","descricao":"Retorno de bem recebido por conta de contrato de comodato ou locação","tipo":"Saída"},
  {"codigo":"5910","descricao":"Remessa em bonificação, doação ou brinde","tipo":"Saída"},
  {"codigo":"5911","descricao":"Remessa de amostra grátis","tipo":"Saída"},
  {"codigo":"5912","descricao":"Remessa de mercadoria ou bem para demonstração, mostruário ou treinamento","tipo":"Saída"},
  {"codigo":"5913","descricao":"Retorno de mercadoria ou bem recebido para demonstração ou mostruário","tipo":"Saída"},
  {"codigo":"5914","descricao":"Remessa de mercadoria ou bem para exposição ou feira","tipo":"Saída"},
  {"codigo":"5915","descricao":"Remessa de mercadoria ou bem para conserto ou reparo","tipo":"Saída"},
  {"codigo":"5916","descricao":"Retorno de mercadoria ou bem recebido para conserto ou reparo","tipo":"Saída"},
  {"codigo":"5917","descricao":"Remessa de mercadoria em consignação mercantil ou industrial","tipo":"Saída"},
  {"codigo":"5918","descricao":"Devolução de mercadoria recebida em consignação mercantil ou industrial","tipo":"Saída"},
  {"codigo":"5919","descricao":"Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, recebida anteriormente em consignação mercantil ou industrial","tipo":"Saída"},
  {"codigo":"5920","descricao":"Remessa de embalagens, bombonas, vasilhames, sacarias, pallets, containers ou assemelhados","tipo":"Saída"},
  {"codigo":"5921","descricao":"Devolução de embalagens, bombonas, vasilhames, sacarias, pallets, containers ou assemelhados","tipo":"Saída"},
  {"codigo":"5922","descricao":"Lançamento efetuado a título de simples faturamento decorrente de venda para entrega futura","tipo":"Saída"},
  {"codigo":"5923","descricao":"Remessa de mercadoria por conta e ordem de terceiros, em venda à ordem ou em operações com armazém geral ou depósito fechado","tipo":"Saída"},
  {"codigo":"5924","descricao":"Remessa para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente","tipo":"Saída"},
  {"codigo":"5925","descricao":"Retorno de mercadoria recebida para industrialização por conta e ordem do adquirente da mercadoria, quando aquela não transitar pelo estabelecimento do adquirente","tipo":"Saída"},
  {"codigo":"5926","descricao":"Lançamento efetuado a título de reclassificação de mercadoria decorrente de formação de kit ou de sua desagregação","tipo":"Saída"},
  {"codigo":"5927","descricao":"Lançamento efetuado a título de baixa de estoque decorrente de perda, roubo, deterioração","tipo":"Saída"},
  {"codigo":"5928","descricao":"Lançamento efetuado a título de baixa de estoque decorrente do encerramento da atividade do estabelecimento da empresa ou transferência por venda do fundo de comércio","tipo":"Saída"},
  {"codigo":"5929","descricao":"Lançamento efetuado em decorrência de emissão de documento fiscal relativo à operação ou prestação também acobertada por documento fiscal do varejo","tipo":"Saída"},
  {"codigo":"5931","descricao":"Lançamento efetuado em decorrência da responsabilidade de retenção do imposto por substituição tributária, atribuída ao remetente ou alienante da mercadoria, pelo serviço de transporte realizado por transportador autônomo ou por transportador não inscrito na unidade da Federação onde iniciado o serviço","tipo":"Saída"},
  {"codigo":"5932","descricao":"Prestação de serviço de transporte iniciada em unidade da Federação diversa daquela onde inscrito o prestador","tipo":"Saída"},
  {"codigo":"5933","descricao":"Prestação de serviço sujeita ao ISSQN","tipo":"Saída"},
  {"codigo":"5934","descricao":"Remessa simbólica de mercadoria depositada em armazém geral ou depósito fechado","tipo":"Saída"},
  {"codigo":"5949","descricao":"Outra saída de mercadoria ou prestação de serviço não especificada","tipo":"Saída"},
  {"codigo":"6101","descricao":"Venda de produção do estabelecimento","tipo":"Saída"},
  {"codigo":"6102","descricao":"Venda de mercadoria adquirida ou recebida de terceiros, ou qualquer venda de mercadoria efetuada pelo MEI com exceção das saídas classificadas nos códigos 6.501, 6.502, 6.504 e 6.505","tipo":"Saída"},
  {"codigo":"6103","descricao":"Venda de produção do estabelecimento, efetuada fora do estabelecimento","tipo":"Saída"},
  {"codigo":"6104","descricao":"Venda de mercadoria adquirida ou recebida de terceiros, efetuada fora do estabelecimento","tipo":"Saída"},
  {"codigo":"6105","descricao":"Venda de produção do estabelecimento armazenada em depósito fechado, armazém geral ou outro estabelecimento da mesma empresa ou de terceiro, que não deva por ele transitar","tipo":"Saída"},
  {"codigo":"6106","descricao":"Venda de mercadoria adquirida ou recebida de terceiros armazenada em depósito fechado, armazém geral ou outro estabelecimento da mesma empresa ou de terceiro, que não deva por ele transitar","tipo":"Saída"},
  {"codigo":"6107","descricao":"Venda de produção do estabelecimento, destinada a não contribuinte","tipo":"Saída"},
  {"codigo":"6108","descricao":"Venda de mercadoria adquirida ou recebida de terceiros, destinada a não contribuinte","tipo":"Saída"},
  {"codigo":"6109","descricao":"Venda de produção do estabelecimento, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio","tipo":"Saída"},
  {"codigo":"6110","descricao":"Venda de mercadoria adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio","tipo":"Saída"},
  {"codigo":"6111","descricao":"Venda de produção do estabelecimento remetida anteriormente em consignação industrial","tipo":"Saída"},
  {"codigo":"6112","descricao":"Venda de mercadoria adquirida ou recebida de terceiros remetida anteriormente em consignação industrial","tipo":"Saída"},
  {"codigo":"6113","descricao":"Venda de produção do estabelecimento remetida anteriormente em consignação mercantil","tipo":"Saída"},
  {"codigo":"6114","descricao":"Venda de mercadoria adquirida ou recebida de terceiros remetida anteriormente em consignação mercantil","tipo":"Saída"},
  {"codigo":"6115","descricao":"Venda de mercadoria adquirida ou recebida de terceiros, recebida anteriormente em consignação mercantil","tipo":"Saída"},
  {"codigo":"6116","descricao":"Venda de produção do estabelecimento originada de encomenda para entrega futura","tipo":"Saída"},
  {"codigo":"6117","descricao":"Venda de mercadoria adquirida ou recebida de terceiros, originada de encomenda para entrega futura","tipo":"Saída"},
  {"codigo":"6118","descricao":"Venda de produção do estabelecimento industrial ou rural, entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem","tipo":"Saída"},
  {"codigo":"6119","descricao":"Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem","tipo":"Saída"},
  {"codigo":"6120","descricao":"Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário pelo vendedor remetente, em venda à ordem","tipo":"Saída"},
  {"codigo":"6122","descricao":"Venda de produção do estabelecimento remetida para industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente","tipo":"Saída"},
  {"codigo":"6123","descricao":"Venda de mercadoria adquirida ou recebida de terceiros remetida para industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente","tipo":"Saída"},
  {"codigo":"6124","descricao":"Industrialização efetuada para outra empresa","tipo":"Saída"},
  {"codigo":"6125","descricao":"Industrialização efetuada para outra empresa quando a mercadoria recebida para utilização no processo de industrialização não transitar pelo estabelecimento adquirente da mercadoria","tipo":"Saída"},
  {"codigo":"6129","descricao":"Venda de mercadoria industrializada e de insumo importado sob o amparo do Regime Aduaneiro Especial de Entreposto Industrial sob Controle Informatizado do Sistema Público de Escrituração Digital (Recof-Sped)","tipo":"Saída"},
  {"codigo":"6131","descricao":"Remessa de produção do estabelecimento, com previsão de posterior ajuste ou fixação de preço, em ato cooperativo","tipo":"Saída"},
  {"codigo":"6132","descricao":"Fixação de preço de produção do estabelecimento, inclusive quando remetidas anteriormente com previsão de posterior ajuste ou fixação de preço, em ato cooperativo","tipo":"Saída"},
  {"codigo":"6151","descricao":"Transferência de produção do estabelecimento","tipo":"Saída"},
  {"codigo":"6152","descricao":"Transferência de mercadoria adquirida ou recebida de terceiros","tipo":"Saída"},
  {"codigo":"6153","descricao":"Transferência de energia elétrica","tipo":"Saída"},
  {"codigo":"6155","descricao":"Transferência de produção do estabelecimento armazenada em depósito fechado, armazém geral ou outro estabelecimento da mesma empresa ou de terceiro, que não deva por ele transitar","tipo":"Saída"},
  {"codigo":"6156","descricao":"Transferência de mercadoria adquirida ou recebida de terceiros armazenada em depósito fechado, armazém geral ou outro estabelecimento da mesma empresa ou de terceiro, que não deva por ele transitar","tipo":"Saída"},
  {"codigo":"6159","descricao":"Fornecimento de produção do estabelecimento em ato cooperativo","tipo":"Saída"},
  {"codigo":"6160","descricao":"Fornecimento de mercadoria adquirida ou recebida de terceiros em ato cooperativo","tipo":"Saída"},
  {"codigo":"6201","descricao":"Devolução de compra para industrialização ou produção rural","tipo":"Saída"},
  {"codigo":"6202","descricao":"Devolução de compra para comercialização, ou qualquer devolução de mercadoria efetuada pelo MEI com exceção das classificadas no código 6.503","tipo":"Saída"},
  {"codigo":"6205","descricao":"Anulação de valor relativo à aquisição de serviço de comunicação","tipo":"Saída"},
  {"codigo":"6206","descricao":"Anulação de valor relativo à aquisição de serviço de transporte","tipo":"Saída"},
  {"codigo":"6207","descricao":"Anulação de valor relativo à compra de energia elétrica","tipo":"Saída"},
  {"codigo":"6208","descricao":"Devolução de mercadoria recebida em transferência para industrialização ou produção rural","tipo":"Saída"},
  {"codigo":"6209","descricao":"Devolução de mercadoria recebida em transferência para comercialização","tipo":"Saída"},
  {"codigo":"6210","descricao":"Devolução de compra para utilização na prestação de serviço","tipo":"Saída"},
  {"codigo":"6213","descricao":"Devolução de entrada, inclusive simbólica, de mercadoria, com previsão de posterior ajuste ou fixação de preço, em ato cooperativo","tipo":"Saída"},
  {"codigo":"6214","descricao":"Devolução referente à fixação de preço de produção do estabelecimento produtor, inclusive quando remetidas anteriormente com previsão de posterior ajuste ou fixação de preço, em ato cooperativo, para comercialização","tipo":"Saída"},
  {"codigo":"6215","descricao":"Devolução referente à fixação de preço de produção do estabelecimento produtor, inclusive quando remetidas anteriormente com previsão de posterior ajuste ou fixação de preço, em ato cooperativo, para industrialização","tipo":"Saída"},
  {"codigo":"6216","descricao":"Devolução de entrada decorrente do fornecimento de produto ou mercadoria em ato cooperativo","tipo":"Saída"},
  {"codigo":"6251","descricao":"Venda de energia elétrica para distribuição ou comercialização","tipo":"Saída"},
  {"codigo":"6252","descricao":"Venda de energia elétrica para estabelecimento industrial","tipo":"Saída"},
  {"codigo":"6253","descricao":"Venda de energia elétrica para estabelecimento comercial","tipo":"Saída"},
  {"codigo":"6254","descricao":"Venda de energia elétrica para estabelecimento prestador de serviço de transporte","tipo":"Saída"},
  {"codigo":"6255","descricao":"Venda de energia elétrica para estabelecimento prestador de serviço de comunicação","tipo":"Saída"},
  {"codigo":"6256","descricao":"Venda de energia elétrica para estabelecimento de produtor rural","tipo":"Saída"},
  {"codigo":"6257","descricao":"Venda de energia elétrica para consumo por demanda contratada","tipo":"Saída"},
  {"codigo":"6258","descricao":"Venda de energia elétrica a não contribuinte","tipo":"Saída"},
  {"codigo":"6301","descricao":"Prestação de serviço de comunicação para execução de serviço da mesma natureza","tipo":"Saída"},
  {"codigo":"6302","descricao":"Prestação de serviço de comunicação a estabelecimento industrial","tipo":"Saída"},
  {"codigo":"6303","descricao":"Prestação de serviço de comunicação a estabelecimento comercial","tipo":"Saída"},
  {"codigo":"6304","descricao":"Prestação de serviço de comunicação a estabelecimento de prestador de serviço de transporte","tipo":"Saída"},
  {"codigo":"6305","descricao":"Prestação de serviço de comunicação a estabelecimento de geradora ou de distribuidora de energia elétrica","tipo":"Saída"},
  {"codigo":"6306","descricao":"Prestação de serviço de comunicação a estabelecimento de produtor rural","tipo":"Saída"},
  {"codigo":"6307","descricao":"Prestação de serviço de comunicação a não contribuinte","tipo":"Saída"},
  {"codigo":"6351","descricao":"Prestação de serviço de transporte para execução de serviço da mesma natureza","tipo":"Saída"},
  {"codigo":"6352","descricao":"Prestação de serviço de transporte a estabelecimento industrial","tipo":"Saída"},
  {"codigo":"6353","descricao":"Prestação de serviço de transporte a estabelecimento comercial","tipo":"Saída"},
  {"codigo":"6354","descricao":"Prestação de serviço de transporte a estabelecimento de prestador de serviço de comunicação","tipo":"Saída"},
  {"codigo":"6355","descricao":"Prestação de serviço de transporte a estabelecimento de geradora ou de distribuidora de energia elétrica","tipo":"Saída"},
  {"codigo":"6356","descricao":"Prestação de serviço de transporte a estabelecimento de produtor rural","tipo":"Saída"},
  {"codigo":"6357","descricao":"Prestação de serviço de transporte a não contribuinte","tipo":"Saída"},
  {"codigo":"6359","descricao":"Prestação de serviço de transporte a contribuinte ou a não contribuinte quando a mercadoria transportada está dispensada de emissão de nota fiscal","tipo":"Saída"},
  {"codigo":"6360","descricao":"Prestação de serviço de transporte a contribuinte substituto em relação ao serviço de transporte","tipo":"Saída"},
  {"codigo":"6401","descricao":"Venda de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária, na condição de contribuinte substituto","tipo":"Saída"},
  {"codigo":"6402","descricao":"Venda de produção do estabelecimento de produto sujeito ao regime de substituição tributária, em operação entre contribuintes substitutos do mesmo produto","tipo":"Saída"},
  {"codigo":"6403","descricao":"Venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária, na condição de contribuinte substituto","tipo":"Saída"},
  {"codigo":"6404","descricao":"Venda de mercadoria sujeita ao regime de substituição tributária, cujo imposto já tenha sido retido anteriormente","tipo":"Saída"},
  {"codigo":"6408","descricao":"Transferência de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária","tipo":"Saída"},
  {"codigo":"6409","descricao":"Transferência de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária","tipo":"Saída"},
  {"codigo":"6410","descricao":"Devolução de compra para industrialização ou produção rural em operação com mercadoria sujeita ao regime de substituição tributária","tipo":"Saída"},
  {"codigo":"6411","descricao":"Devolução de compra para comercialização em operação com mercadoria sujeita ao regime de substituição tributária","tipo":"Saída"},
  {"codigo":"6412","descricao":"Devolução de bem do ativo imobilizado, em operação com mercadoria sujeita ao regime de substituição tributária","tipo":"Saída"},
  {"codigo":"6413","descricao":"Devolução de mercadoria destinada para uso ou consumo, em operação com mercadoria sujeita ao regime de substituição tributária","tipo":"Saída"},
  {"codigo":"6414","descricao":"Remessa de produção do estabelecimento para venda fora do estabelecimento em operação com produto sujeito ao regime de substituição tributária","tipo":"Saída"},
  {"codigo":"6415","descricao":"Remessa de mercadoria adquirida ou recebida de terceiros para venda fora do estabelecimento, em operação com mercadoria sujeita ao regime de substituição tributária","tipo":"Saída"},
  {"codigo":"6451","descricao":"Remessa de animal - Sistema de Integração e Parceria Rural","tipo":"Saída"},
  {"codigo":"6452","descricao":"Remessa de insumo - Sistema de Integração e Parceria Rural","tipo":"Saída"},
  {"codigo":"6453","descricao":"Retorno de animal ou da produção - Sistema de Integração e Parceria Rural","tipo":"Saída"},
  {"codigo":"6454","descricao":"Retorno simbólico de animal ou da produção - Sistema de Integração e Parceria Rural","tipo":"Saída"},
  {"codigo":"6455","descricao":"Retorno de insumos não utilizados na produção - Sistema de Integração e Parceria Rural","tipo":"Saída"},
  {"codigo":"6456","descricao":"Saída referente à remuneração do produtor - Sistema de Integração e Parceria Rural","tipo":"Saída"},
  {"codigo":"6501","descricao":"Remessa de produção do estabelecimento, com fim específico de exportação","tipo":"Saída"},
  {"codigo":"6502","descricao":"Remessa de mercadoria adquirida ou recebida de terceiros, com fim específico de exportação","tipo":"Saída"},
  {"codigo":"6503","descricao":"Devolução de mercadoria recebida com fim específico de exportação","tipo":"Saída"},
  {"codigo":"6504","descricao":"Remessa de mercadorias para formação de lote de exportação, de produtos industrializados ou produzidos pelo próprio estabelecimento","tipo":"Saída"},
  {"codigo":"6505","descricao":"Remessa de mercadorias, adquiridas ou recebidas de terceiros, para formação de lote de exportação","tipo":"Saída"},
  {"codigo":"6551","descricao":"Venda de bem do ativo imobilizado","tipo":"Saída"},
  {"codigo":"6552","descricao":"Transferência de bem do ativo imobilizado","tipo":"Saída"},
  {"codigo":"6553","descricao":"Devolução de compra de bem para o ativo imobilizado","tipo":"Saída"},
  {"codigo":"6554","descricao":"Remessa de bem do ativo imobilizado para uso fora do estabelecimento","tipo":"Saída"},
  {"codigo":"6555","descricao":"Devolução de bem do ativo imobilizado de terceiro, recebido para uso no estabelecimento","tipo":"Saída"},
  {"codigo":"6556","descricao":"Devolução de compra de material para uso ou consumo","tipo":"Saída"},
  {"codigo":"6557","descricao":"Transferência de material para uso ou consumo","tipo":"Saída"},
  {"codigo":"6603","descricao":"Ressarcimento de ICMS retido por substituição tributária","tipo":"Saída"},
  {"codigo":"6651","descricao":"Venda de combustíveis ou lubrificantes de produção do estabelecimento destinados à industrialização subsequente","tipo":"Saída"},
  {"codigo":"6652","descricao":"Venda de combustíveis ou lubrificantes de produção do estabelecimento destinados à comercialização","tipo":"Saída"},
  {"codigo":"6653","descricao":"Venda de combustíveis ou lubrificantes de produção do estabelecimento destinados a consumidor ou usuário final","tipo":"Saída"},
  {"codigo":"6654","descricao":"Venda de combustíveis ou lubrificantes adquiridos ou recebidos de terceiros destinados à industrialização subsequente","tipo":"Saída"},
  {"codigo":"6655","descricao":"Venda de combustíveis ou lubrificantes adquiridos ou recebidos de terceiros destinados à comercialização","tipo":"Saída"},
  {"codigo":"6656","descricao":"Venda de combustíveis ou lubrificantes adquiridos ou recebidos de terceiros destinados a consumidor ou usuário final","tipo":"Saída"},
  {"codigo":"6657","descricao":"Remessa de combustíveis ou lubrificantes adquiridos ou recebidos de terceiros para venda fora do estabelecimento","tipo":"Saída"},
  {"codigo":"6658","descricao":"Transferência de combustíveis ou lubrificantes de produção do estabelecimento","tipo":"Saída"},
  {"codigo":"6659","descricao":"Transferência de combustíveis ou lubrificantes adquiridos ou recebidos de terceiros","tipo":"Saída"},
  {"codigo":"6660","descricao":"Devolução de compra de combustíveis ou lubrificantes adquiridos para industrialização subsequente","tipo":"Saída"},
  {"codigo":"6661","descricao":"Devolução de compra de combustíveis ou lubrificantes adquiridos para comercialização","tipo":"Saída"},
  {"codigo":"6662","descricao":"Devolução de compra de combustíveis ou lubrificantes adquiridos por consumidor ou usuário final","tipo":"Saída"},
  {"codigo":"6663","descricao":"Remessa para armazenagem de combustíveis ou lubrificantes","tipo":"Saída"},
  {"codigo":"6664","descricao":"Retorno de combustíveis ou lubrificantes recebidos para armazenagem","tipo":"Saída"},
  {"codigo":"6665","descricao":"Retorno simbólico de combustíveis ou lubrificantes recebidos para armazenagem","tipo":"Saída"},
  {"codigo":"6666","descricao":"Remessa por conta e ordem de terceiros de combustíveis ou lubrificantes recebidos para armazenagem","tipo":"Saída"},
  {"codigo":"6667","descricao":"Venda de combustíveis ou lubrificantes a consumidor ou usuário final estabelecido em outra unidade da Federação diferente da que ocorrer o consumo","tipo":"Saída"},
  {"codigo":"6901","descricao":"Remessa para industrialização por encomenda","tipo":"Saída"},
  {"codigo":"6902","descricao":"Retorno de mercadoria utilizada na industrialização por encomenda","tipo":"Saída"},
  {"codigo":"6903","descricao":"Retorno de mercadoria recebida para industrialização e não aplicada no referido processo","tipo":"Saída"},
  {"codigo":"6904","descricao":"Remessa para venda fora do estabelecimento, ou qualquer remessa efetuada pelo MEI com exceção das classificadas nos códigos 6.502 e 6.505","tipo":"Saída"},
  {"codigo":"6905","descricao":"Remessa para depósito fechado, armazém geral ou outro estabelecimento da mesma empresa ou de terceiro","tipo":"Saída"},
  {"codigo":"6906","descricao":"Retorno de mercadoria depositada em depósito fechado, armazém geral ou outro estabelecimento da mesma empresa ou de terceiro","tipo":"Saída"},
  {"codigo":"6907","descricao":"Retorno simbólico de mercadoria depositada em depósito fechado, armazém geral ou outro estabelecimento da mesma empresa ou de terceiro","tipo":"Saída"},
  {"codigo":"6908","descricao":"Remessa de bem por conta de contrato de comodato ou locação","tipo":"Saída"},
  {"codigo":"6909","descricao":"Retorno de bem recebido por conta de contrato de comodato ou locação","tipo":"Saída"},
  {"codigo":"6910","descricao":"Remessa em bonificação, doação ou brinde","tipo":"Saída"},
  {"codigo":"6911","descricao":"Remessa de amostra grátis","tipo":"Saída"},
  {"codigo":"6912","descricao":"Remessa de mercadoria ou bem para demonstração, mostruário ou treinamento","tipo":"Saída"},
  {"codigo":"6913","descricao":"Retorno de mercadoria ou bem recebido para demonstração ou mostruário","tipo":"Saída"},
  {"codigo":"6914","descricao":"Remessa de mercadoria ou bem para exposição ou feira","tipo":"Saída"},
  {"codigo":"6915","descricao":"Remessa de mercadoria ou bem para conserto ou reparo","tipo":"Saída"},
  {"codigo":"6916","descricao":"Retorno de mercadoria ou bem recebido para conserto ou reparo","tipo":"Saída"},
  {"codigo":"6917","descricao":"Remessa de mercadoria em consignação mercantil ou industrial","tipo":"Saída"},
  {"codigo":"6918","descricao":"Devolução de mercadoria recebida em consignação mercantil ou industrial","tipo":"Saída"},
  {"codigo":"6919","descricao":"Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, recebida anteriormente em consignação mercantil ou industrial","tipo":"Saída"},
  {"codigo":"6920","descricao":"Remessa de embalagens, bombonas, vasilhames, sacarias, pallets, containers ou assemelhados","tipo":"Saída"},
  {"codigo":"6921","descricao":"Devolução de embalagens, bombonas, vasilhames, sacarias, pallets, containers ou assemelhados","tipo":"Saída"},
  {"codigo":"6922","descricao":"Lançamento efetuado a título de simples faturamento decorrente de venda para entrega futura","tipo":"Saída"},
  {"codigo":"6923","descricao":"Remessa de mercadoria por conta e ordem de terceiros, em venda à ordem ou em operações com armazém geral ou depósito fechado","tipo":"Saída"},
  {"codigo":"6924","descricao":"Remessa para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente","tipo":"Saída"},
  {"codigo":"6925","descricao":"Retorno de mercadoria recebida para industrialização por conta e ordem do adquirente da mercadoria, quando aquela não transitar pelo estabelecimento do adquirente","tipo":"Saída"},
  {"codigo":"6929","descricao":"Lançamento efetuado em decorrência de emissão de documento fiscal relativo à operação ou prestação também acobertada por documento fiscal do varejo","tipo":"Saída"},
  {"codigo":"6931","descricao":"Lançamento efetuado em decorrência da responsabilidade de retenção do imposto por substituição tributária, atribuída ao remetente ou alienante da mercadoria, pelo serviço de transporte realizado por transportador autônomo ou por transportador não inscrito na unidade da Federação onde iniciado o serviço","tipo":"Saída"},
  {"codigo":"6932","descricao":"Prestação de serviço de transporte iniciada em unidade da Federação diversa daquela onde inscrito o prestador","tipo":"Saída"},
  {"codigo":"6933","descricao":"Prestação de serviço sujeita ao ISSQN","tipo":"Saída"},
  {"codigo":"6934","descricao":"Remessa simbólica de mercadoria depositada em armazém geral ou depósito fechado","tipo":"Saída"},
  {"codigo":"6949","descricao":"Outra saída de mercadoria ou prestação de serviço não especificada","tipo":"Saída"},
  {"codigo":"7101","descricao":"Venda de produção do estabelecimento","tipo":"Saída"},
  {"codigo":"7102","descricao":"Venda de mercadoria adquirida ou recebida de terceiros","tipo":"Saída"},
  {"codigo":"7105","descricao":"Venda de produção do estabelecimento armazenada em depósito fechado, armazém geral ou outro estabelecimento da mesma empresa ou de terceiro, que não deva por ele transitar","tipo":"Saída"},
  {"codigo":"7106","descricao":"Venda de mercadoria adquirida ou recebida de terceiros armazenada em depósito fechado, armazém geral ou outro estabelecimento da mesma empresa ou de terceiro, que não deva por ele transitar","tipo":"Saída"},
  {"codigo":"7127","descricao":"Venda de produção do estabelecimento sob o regime de “drawback”","tipo":"Saída"},
  {"codigo":"7129","descricao":"Venda de produção do estabelecimento ao mercado externo de mercadoria industrializada sob o amparo do Regime Aduaneiro Especial de Entreposto Industrial sob Controle Informatizado do Sistema Público de Escrituração Digital (Recof-Sped)","tipo":"Saída"},
  {"codigo":"7201","descricao":"Devolução de compra para industrialização ou produção rural","tipo":"Saída"},
  {"codigo":"7202","descricao":"Devolução de compra para comercialização","tipo":"Saída"},
  {"codigo":"7205","descricao":"Anulação de valor relativo à aquisição de serviço de comunicação","tipo":"Saída"},
  {"codigo":"7206","descricao":"Anulação de valor relativo à aquisição de serviço de transporte","tipo":"Saída"},
  {"codigo":"7207","descricao":"Anulação de valor relativo à compra de energia elétrica","tipo":"Saída"},
  {"codigo":"7210","descricao":"Devolução de compra para utilização na prestação de serviço","tipo":"Saída"},
  {"codigo":"7211","descricao":"Devolução de compras para industrialização sob o regime de “drawback”","tipo":"Saída"},
  {"codigo":"7212","descricao":"Devolução de compras para industrialização sob o regime de Regime Aduaneiro Especial de Entreposto Industrial sob Controle Informatizado do Sistema Público de Escrituração Digital (Recof-Sped)","tipo":"Saída"},
  {"codigo":"7251","descricao":"Venda de energia elétrica para o exterior","tipo":"Saída"},
  {"codigo":"7301","descricao":"Prestação de serviço de comunicação para execução de serviço da mesma natureza","tipo":"Saída"},
  {"codigo":"7358","descricao":"Prestação de serviço de transporte","tipo":"Saída"},
  {"codigo":"7501","descricao":"Exportação de mercadorias recebidas com fim específico de exportação","tipo":"Saída"},
  {"codigo":"7504","descricao":"Exportação de mercadoria que foi objeto de formação de lote de exportação","tipo":"Saída"},
  {"codigo":"7551","descricao":"Venda de bem do ativo imobilizado","tipo":"Saída"},
  {"codigo":"7552","descricao":"Saída de produto destinado para uso ou consumo de bordo, em embarcações ou aeronaves exclusivamente em tráfego internacional com destino ao exterior","tipo":"Saída"},
  {"codigo":"7553","descricao":"Devolução de compra de bem para o ativo imobilizado","tipo":"Saída"},
  {"codigo":"7556","descricao":"Devolução de compra de material para uso ou consumo","tipo":"Saída"},
  {"codigo":"7651","descricao":"Venda de combustíveis ou lubrificantes de produção do estabelecimento","tipo":"Saída"},
  {"codigo":"7654","descricao":"Venda de combustíveis ou lubrificantes adquiridos ou recebidos de terceiros","tipo":"Saída"},
  {"codigo":"7667","descricao":"Saída de combustíveis ou lubrificantes a consumidor ou usuário final","tipo":"Saída"},
  {"codigo":"7930","descricao":"Lançamento efetuado a título de devolução de bem cuja entrada tenha ocorrido sob amparo de regime especial aduaneiro de admissão temporária","tipo":"Saída"},
  {"codigo":"7949","descricao":"Outra saída de mercadoria ou prestação de serviço não especificada","tipo":"Saída"},
];

export const SEED_CST_ICMS: TabelaAuxiliarSimples[] = [
{"codigo":"000","descricao":"Tributada integralmente"},
  {"codigo":"010","descricao":"Tributada e com cobrança do ICMS por substituição tributária"},
  {"codigo":"020","descricao":"Com redução de base de cálculo"},
  {"codigo":"030","descricao":"Isenta ou não tributada e com cobrança do ICMS por ST"},
  {"codigo":"040","descricao":"Isenta"},
  {"codigo":"041","descricao":"Não tributada"},
  {"codigo":"050","descricao":"Suspensão"},
  {"codigo":"051","descricao":"Diferimento"},
  {"codigo":"060","descricao":"ICMS cobrado anteriormente por substituição tributária"},
  {"codigo":"070","descricao":"Com redução de base de cálculo e cobrança do ICMS por ST"},
  {"codigo":"090","descricao":"Outros"},
  {"codigo":"101","descricao":"Tributada com permissão de crédito (Simples Nacional)"},
  {"codigo":"102","descricao":"Tributada sem permissão de crédito (Simples Nacional)"},
  {"codigo":"103","descricao":"Isenção do ICMS para faixa de receita bruta (Simples Nacional)"},
  {"codigo":"201","descricao":"Tributada com permissão de crédito e com cobrança do ICMS por ST (Simples)"},
  {"codigo":"202","descricao":"Tributada sem permissão de crédito e com cobrança do ICMS por ST (Simples)"},
  {"codigo":"203","descricao":"Isenção do ICMS para faixa de receita bruta e com cobrança do ICMS por ST (Simples)"},
  {"codigo":"300","descricao":"Imune"},
  {"codigo":"400","descricao":"Não tributada pelo Simples Nacional"},
  {"codigo":"500","descricao":"ICMS cobrado anteriormente por ST ou por antecipação (Simples)"},
  {"codigo":"900","descricao":"Outros"},
];

export const SEED_CST_PISCOFINS: TabelaAuxiliarSimples[] = [
{"codigo":"01","descricao":"Operação Tributável com Alíquota Básica"},
  {"codigo":"02","descricao":"Operação Tributável com Alíquota Diferenciada"},
  {"codigo":"03","descricao":"Operação Tributável com Alíquota por Unidade de Medida de Produto"},
  {"codigo":"04","descricao":"Operação Tributável Monofásica - Revenda a Alíquota Zero"},
  {"codigo":"05","descricao":"Operação Tributável por Substituição Tributária"},
  {"codigo":"06","descricao":"Operação Tributável a Alíquota Zero"},
  {"codigo":"07","descricao":"Operação Isenta da Contribuição"},
  {"codigo":"08","descricao":"Operação Sem Incidência da Contribuição"},
  {"codigo":"09","descricao":"Operação com Suspensão da Contribuição"},
  {"codigo":"49","descricao":"Outras Operações de Saída"},
  {"codigo":"99","descricao":"Outras Operações"},
];
